// Code generated by protoc-gen-go. DO NOT EDIT.
// source: communicationmethodfield.proto

package communicationmethodfield

import (
	context "context"
	fmt "fmt"
	audit "github.com/bungysheep/contact-management/pkg/api/v1/audit"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommunicationMethodField struct {
	ContactSystemCode       string       `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string       `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	FieldCode               string       `protobuf:"bytes,3,opt,name=field_code,json=fieldCode,proto3" json:"field_code,omitempty"`
	Caption                 string       `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	Sequence                int64        `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Audit                   *audit.Audit `protobuf:"bytes,6,opt,name=audit,proto3" json:"audit,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}     `json:"-"`
	XXX_unrecognized        []byte       `json:"-"`
	XXX_sizecache           int32        `json:"-"`
}

func (m *CommunicationMethodField) Reset()         { *m = CommunicationMethodField{} }
func (m *CommunicationMethodField) String() string { return proto.CompactTextString(m) }
func (*CommunicationMethodField) ProtoMessage()    {}
func (*CommunicationMethodField) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{0}
}

func (m *CommunicationMethodField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunicationMethodField.Unmarshal(m, b)
}
func (m *CommunicationMethodField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunicationMethodField.Marshal(b, m, deterministic)
}
func (m *CommunicationMethodField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunicationMethodField.Merge(m, src)
}
func (m *CommunicationMethodField) XXX_Size() int {
	return xxx_messageInfo_CommunicationMethodField.Size(m)
}
func (m *CommunicationMethodField) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunicationMethodField.DiscardUnknown(m)
}

var xxx_messageInfo_CommunicationMethodField proto.InternalMessageInfo

func (m *CommunicationMethodField) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *CommunicationMethodField) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

func (m *CommunicationMethodField) GetFieldCode() string {
	if m != nil {
		return m.FieldCode
	}
	return ""
}

func (m *CommunicationMethodField) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *CommunicationMethodField) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *CommunicationMethodField) GetAudit() *audit.Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

type DoReadRequest struct {
	ContactSystemCode       string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	FieldCode               string   `protobuf:"bytes,3,opt,name=field_code,json=fieldCode,proto3" json:"field_code,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DoReadRequest) Reset()         { *m = DoReadRequest{} }
func (m *DoReadRequest) String() string { return proto.CompactTextString(m) }
func (*DoReadRequest) ProtoMessage()    {}
func (*DoReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{1}
}

func (m *DoReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadRequest.Unmarshal(m, b)
}
func (m *DoReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadRequest.Marshal(b, m, deterministic)
}
func (m *DoReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadRequest.Merge(m, src)
}
func (m *DoReadRequest) XXX_Size() int {
	return xxx_messageInfo_DoReadRequest.Size(m)
}
func (m *DoReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadRequest proto.InternalMessageInfo

func (m *DoReadRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoReadRequest) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

func (m *DoReadRequest) GetFieldCode() string {
	if m != nil {
		return m.FieldCode
	}
	return ""
}

type DoReadResponse struct {
	CommunicationMethodField *CommunicationMethodField `protobuf:"bytes,1,opt,name=communication_method_field,json=communicationMethodField,proto3" json:"communication_method_field,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *DoReadResponse) Reset()         { *m = DoReadResponse{} }
func (m *DoReadResponse) String() string { return proto.CompactTextString(m) }
func (*DoReadResponse) ProtoMessage()    {}
func (*DoReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{2}
}

func (m *DoReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadResponse.Unmarshal(m, b)
}
func (m *DoReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadResponse.Marshal(b, m, deterministic)
}
func (m *DoReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadResponse.Merge(m, src)
}
func (m *DoReadResponse) XXX_Size() int {
	return xxx_messageInfo_DoReadResponse.Size(m)
}
func (m *DoReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadResponse proto.InternalMessageInfo

func (m *DoReadResponse) GetCommunicationMethodField() *CommunicationMethodField {
	if m != nil {
		return m.CommunicationMethodField
	}
	return nil
}

type DoReadAllRequest struct {
	ContactSystemCode       string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DoReadAllRequest) Reset()         { *m = DoReadAllRequest{} }
func (m *DoReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*DoReadAllRequest) ProtoMessage()    {}
func (*DoReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{3}
}

func (m *DoReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadAllRequest.Unmarshal(m, b)
}
func (m *DoReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadAllRequest.Marshal(b, m, deterministic)
}
func (m *DoReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadAllRequest.Merge(m, src)
}
func (m *DoReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_DoReadAllRequest.Size(m)
}
func (m *DoReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadAllRequest proto.InternalMessageInfo

func (m *DoReadAllRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoReadAllRequest) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

type DoReadAllResponse struct {
	CommunicationMethodField []*CommunicationMethodField `protobuf:"bytes,1,rep,name=communication_method_field,json=communicationMethodField,proto3" json:"communication_method_field,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                    `json:"-"`
	XXX_unrecognized         []byte                      `json:"-"`
	XXX_sizecache            int32                       `json:"-"`
}

func (m *DoReadAllResponse) Reset()         { *m = DoReadAllResponse{} }
func (m *DoReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*DoReadAllResponse) ProtoMessage()    {}
func (*DoReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{4}
}

func (m *DoReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadAllResponse.Unmarshal(m, b)
}
func (m *DoReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadAllResponse.Marshal(b, m, deterministic)
}
func (m *DoReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadAllResponse.Merge(m, src)
}
func (m *DoReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_DoReadAllResponse.Size(m)
}
func (m *DoReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadAllResponse proto.InternalMessageInfo

func (m *DoReadAllResponse) GetCommunicationMethodField() []*CommunicationMethodField {
	if m != nil {
		return m.CommunicationMethodField
	}
	return nil
}

type DoSaveRequest struct {
	CommunicationMethodField *CommunicationMethodField `protobuf:"bytes,1,opt,name=communication_method_field,json=communicationMethodField,proto3" json:"communication_method_field,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *DoSaveRequest) Reset()         { *m = DoSaveRequest{} }
func (m *DoSaveRequest) String() string { return proto.CompactTextString(m) }
func (*DoSaveRequest) ProtoMessage()    {}
func (*DoSaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{5}
}

func (m *DoSaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSaveRequest.Unmarshal(m, b)
}
func (m *DoSaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSaveRequest.Marshal(b, m, deterministic)
}
func (m *DoSaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSaveRequest.Merge(m, src)
}
func (m *DoSaveRequest) XXX_Size() int {
	return xxx_messageInfo_DoSaveRequest.Size(m)
}
func (m *DoSaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoSaveRequest proto.InternalMessageInfo

func (m *DoSaveRequest) GetCommunicationMethodField() *CommunicationMethodField {
	if m != nil {
		return m.CommunicationMethodField
	}
	return nil
}

type DoSaveResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoSaveResponse) Reset()         { *m = DoSaveResponse{} }
func (m *DoSaveResponse) String() string { return proto.CompactTextString(m) }
func (*DoSaveResponse) ProtoMessage()    {}
func (*DoSaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{6}
}

func (m *DoSaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSaveResponse.Unmarshal(m, b)
}
func (m *DoSaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSaveResponse.Marshal(b, m, deterministic)
}
func (m *DoSaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSaveResponse.Merge(m, src)
}
func (m *DoSaveResponse) XXX_Size() int {
	return xxx_messageInfo_DoSaveResponse.Size(m)
}
func (m *DoSaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoSaveResponse proto.InternalMessageInfo

func (m *DoSaveResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type DoDeleteRequest struct {
	ContactSystemCode       string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	FieldCode               string   `protobuf:"bytes,3,opt,name=field_code,json=fieldCode,proto3" json:"field_code,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DoDeleteRequest) Reset()         { *m = DoDeleteRequest{} }
func (m *DoDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DoDeleteRequest) ProtoMessage()    {}
func (*DoDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{7}
}

func (m *DoDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoDeleteRequest.Unmarshal(m, b)
}
func (m *DoDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoDeleteRequest.Marshal(b, m, deterministic)
}
func (m *DoDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoDeleteRequest.Merge(m, src)
}
func (m *DoDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DoDeleteRequest.Size(m)
}
func (m *DoDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoDeleteRequest proto.InternalMessageInfo

func (m *DoDeleteRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoDeleteRequest) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

func (m *DoDeleteRequest) GetFieldCode() string {
	if m != nil {
		return m.FieldCode
	}
	return ""
}

type DoDeleteResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoDeleteResponse) Reset()         { *m = DoDeleteResponse{} }
func (m *DoDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DoDeleteResponse) ProtoMessage()    {}
func (*DoDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{8}
}

func (m *DoDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoDeleteResponse.Unmarshal(m, b)
}
func (m *DoDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoDeleteResponse.Marshal(b, m, deterministic)
}
func (m *DoDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoDeleteResponse.Merge(m, src)
}
func (m *DoDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DoDeleteResponse.Size(m)
}
func (m *DoDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoDeleteResponse proto.InternalMessageInfo

func (m *DoDeleteResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*CommunicationMethodField)(nil), "v1.CommunicationMethodField")
	proto.RegisterType((*DoReadRequest)(nil), "v1.DoReadRequest")
	proto.RegisterType((*DoReadResponse)(nil), "v1.DoReadResponse")
	proto.RegisterType((*DoReadAllRequest)(nil), "v1.DoReadAllRequest")
	proto.RegisterType((*DoReadAllResponse)(nil), "v1.DoReadAllResponse")
	proto.RegisterType((*DoSaveRequest)(nil), "v1.DoSaveRequest")
	proto.RegisterType((*DoSaveResponse)(nil), "v1.DoSaveResponse")
	proto.RegisterType((*DoDeleteRequest)(nil), "v1.DoDeleteRequest")
	proto.RegisterType((*DoDeleteResponse)(nil), "v1.DoDeleteResponse")
}

func init() { proto.RegisterFile("communicationmethodfield.proto", fileDescriptor_17ca2fbec7e6e1de) }

var fileDescriptor_17ca2fbec7e6e1de = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x95, 0xb7, 0x6c, 0x69, 0xa7, 0xe2, 0xa3, 0xde, 0x05, 0x42, 0x04, 0x6c, 0x95, 0x53, 0x85,
	0x44, 0xa2, 0x16, 0x21, 0x21, 0x6e, 0xcb, 0x56, 0x9c, 0x80, 0x43, 0x7a, 0xdb, 0x4b, 0xe5, 0x3a,
	0x43, 0x1b, 0x6d, 0x62, 0x87, 0xda, 0x89, 0xb4, 0x17, 0x7e, 0x08, 0xe2, 0x67, 0x72, 0xe4, 0x80,
	0x6c, 0x27, 0xbb, 0x0d, 0x50, 0x84, 0x84, 0x10, 0x3d, 0xfa, 0x8d, 0x5f, 0xde, 0xbc, 0x79, 0x13,
	0xc3, 0x13, 0x2e, 0xf3, 0xbc, 0x14, 0x29, 0x67, 0x3a, 0x95, 0x22, 0x47, 0xbd, 0x96, 0xc9, 0x87,
	0x14, 0xb3, 0x24, 0x2c, 0x36, 0x52, 0x4b, 0x7a, 0x50, 0x4d, 0xfc, 0x01, 0x2b, 0x93, 0x54, 0x3b,
	0x20, 0xf8, 0x46, 0xc0, 0x3b, 0xdb, 0xe6, 0xbc, 0xb3, 0x9c, 0x37, 0x86, 0x43, 0x43, 0x38, 0xe2,
	0x52, 0x68, 0xc6, 0xf5, 0x42, 0x5d, 0x2a, 0x8d, 0xf9, 0x82, 0xcb, 0x04, 0x3d, 0x32, 0x22, 0xe3,
	0x7e, 0x3c, 0xac, 0x4b, 0x73, 0x5b, 0x39, 0x93, 0x09, 0xd2, 0x57, 0xf0, 0xb0, 0xa5, 0xbf, 0x70,
	0x0d, 0x38, 0xd6, 0x81, 0x65, 0x3d, 0xe0, 0x3f, 0x8b, 0x59, 0xee, 0x63, 0x00, 0xdb, 0xa8, 0xbb,
	0xdc, 0xb1, 0x97, 0xfb, 0x16, 0xb1, 0x65, 0x0f, 0x6e, 0x72, 0x56, 0x18, 0x8e, 0x77, 0xc3, 0xd6,
	0x9a, 0x23, 0xf5, 0xa1, 0xa7, 0xf0, 0x63, 0x89, 0x82, 0xa3, 0x77, 0x38, 0x22, 0xe3, 0x4e, 0x7c,
	0x75, 0xa6, 0x27, 0x70, 0x68, 0xcd, 0x7a, 0xdd, 0x11, 0x19, 0x0f, 0xa6, 0xfd, 0xb0, 0x9a, 0x84,
	0xa7, 0x06, 0x88, 0x1d, 0x1e, 0x7c, 0x26, 0x70, 0x6b, 0x26, 0x63, 0x64, 0x49, 0x6c, 0x38, 0x4a,
	0xef, 0x91, 0xe7, 0x20, 0x83, 0xdb, 0x4d, 0x6f, 0xaa, 0x90, 0x42, 0x21, 0x3d, 0x07, 0xff, 0x97,
	0x62, 0x96, 0x63, 0x7b, 0x1c, 0x4c, 0x1f, 0x19, 0x93, 0xbb, 0x22, 0x8d, 0x3d, 0xbe, 0xa3, 0x12,
	0x7c, 0x82, 0xbb, 0x4e, 0xed, 0x34, 0xcb, 0xfe, 0xc3, 0x30, 0x02, 0x09, 0xc3, 0x2d, 0xfd, 0x3f,
	0x34, 0xdc, 0xf9, 0x0b, 0xc3, 0x17, 0x26, 0xfa, 0x39, 0xab, 0xb0, 0x71, 0xfb, 0x2f, 0xa7, 0x3b,
	0x36, 0x59, 0x3a, 0xb1, 0xda, 0xda, 0x7d, 0xe8, 0x6e, 0x50, 0x95, 0x99, 0xb6, 0x5f, 0xee, 0xc5,
	0xf5, 0x29, 0xf8, 0x42, 0xe0, 0xce, 0x4c, 0xce, 0x30, 0x43, 0x8d, 0x7b, 0xb8, 0x94, 0x4f, 0xcd,
	0x9a, 0x34, 0xdd, 0xfd, 0xde, 0xca, 0xf4, 0x2b, 0x81, 0x93, 0x5d, 0xb3, 0x9a, 0xe3, 0xa6, 0x4a,
	0x39, 0xd2, 0x08, 0xba, 0x2e, 0x76, 0x3a, 0x34, 0xa3, 0x6d, 0xfd, 0x8c, 0x3e, 0xdd, 0x86, 0x6a,
	0xb1, 0x97, 0xd0, 0xbf, 0xda, 0x13, 0x7a, 0x7c, 0x7d, 0xe1, 0x7a, 0x6d, 0xfd, 0x7b, 0x3f, 0xa0,
	0x35, 0xd3, 0x4a, 0x99, 0x0c, 0x1a, 0xa9, 0xad, 0xf0, 0x1b, 0xa9, 0x56, 0x44, 0x2f, 0xa0, 0xd7,
	0x78, 0xa5, 0x47, 0xae, 0xde, 0xca, 0xc5, 0x3f, 0x6e, 0x83, 0x8e, 0xf6, 0xfa, 0xfd, 0xf9, 0xdb,
	0x55, 0xaa, 0xd7, 0xe5, 0x32, 0xe4, 0x32, 0x8f, 0x96, 0xa5, 0x58, 0x5d, 0xaa, 0x35, 0x62, 0x11,
	0xd5, 0x41, 0x3d, 0xcb, 0x99, 0x60, 0x2b, 0xcc, 0x51, 0xe8, 0xa8, 0xb8, 0x58, 0x45, 0xac, 0x48,
	0xa3, 0x6a, 0x12, 0xed, 0x7a, 0xba, 0x97, 0x5d, 0xfb, 0x54, 0x3f, 0xff, 0x1e, 0x00, 0x00, 0xff,
	0xff, 0x5c, 0x64, 0x39, 0xb6, 0xdd, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommunicationMethodFieldServiceClient is the client API for CommunicationMethodFieldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommunicationMethodFieldServiceClient interface {
	DoRead(ctx context.Context, in *DoReadRequest, opts ...grpc.CallOption) (*DoReadResponse, error)
	DoReadAll(ctx context.Context, in *DoReadAllRequest, opts ...grpc.CallOption) (*DoReadAllResponse, error)
	DoSave(ctx context.Context, in *DoSaveRequest, opts ...grpc.CallOption) (*DoSaveResponse, error)
	DoDelete(ctx context.Context, in *DoDeleteRequest, opts ...grpc.CallOption) (*DoDeleteResponse, error)
}

type communicationMethodFieldServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommunicationMethodFieldServiceClient(cc *grpc.ClientConn) CommunicationMethodFieldServiceClient {
	return &communicationMethodFieldServiceClient{cc}
}

func (c *communicationMethodFieldServiceClient) DoRead(ctx context.Context, in *DoReadRequest, opts ...grpc.CallOption) (*DoReadResponse, error) {
	out := new(DoReadResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodFieldService/DoRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodFieldServiceClient) DoReadAll(ctx context.Context, in *DoReadAllRequest, opts ...grpc.CallOption) (*DoReadAllResponse, error) {
	out := new(DoReadAllResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodFieldService/DoReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodFieldServiceClient) DoSave(ctx context.Context, in *DoSaveRequest, opts ...grpc.CallOption) (*DoSaveResponse, error) {
	out := new(DoSaveResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodFieldService/DoSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodFieldServiceClient) DoDelete(ctx context.Context, in *DoDeleteRequest, opts ...grpc.CallOption) (*DoDeleteResponse, error) {
	out := new(DoDeleteResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodFieldService/DoDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicationMethodFieldServiceServer is the server API for CommunicationMethodFieldService service.
type CommunicationMethodFieldServiceServer interface {
	DoRead(context.Context, *DoReadRequest) (*DoReadResponse, error)
	DoReadAll(context.Context, *DoReadAllRequest) (*DoReadAllResponse, error)
	DoSave(context.Context, *DoSaveRequest) (*DoSaveResponse, error)
	DoDelete(context.Context, *DoDeleteRequest) (*DoDeleteResponse, error)
}

// UnimplementedCommunicationMethodFieldServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommunicationMethodFieldServiceServer struct {
}

func (*UnimplementedCommunicationMethodFieldServiceServer) DoRead(ctx context.Context, req *DoReadRequest) (*DoReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoRead not implemented")
}
func (*UnimplementedCommunicationMethodFieldServiceServer) DoReadAll(ctx context.Context, req *DoReadAllRequest) (*DoReadAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoReadAll not implemented")
}
func (*UnimplementedCommunicationMethodFieldServiceServer) DoSave(ctx context.Context, req *DoSaveRequest) (*DoSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSave not implemented")
}
func (*UnimplementedCommunicationMethodFieldServiceServer) DoDelete(ctx context.Context, req *DoDeleteRequest) (*DoDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoDelete not implemented")
}

func RegisterCommunicationMethodFieldServiceServer(s *grpc.Server, srv CommunicationMethodFieldServiceServer) {
	s.RegisterService(&_CommunicationMethodFieldService_serviceDesc, srv)
}

func _CommunicationMethodFieldService_DoRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodFieldServiceServer).DoRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodFieldService/DoRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodFieldServiceServer).DoRead(ctx, req.(*DoReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodFieldService_DoReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodFieldServiceServer).DoReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodFieldService/DoReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodFieldServiceServer).DoReadAll(ctx, req.(*DoReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodFieldService_DoSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodFieldServiceServer).DoSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodFieldService/DoSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodFieldServiceServer).DoSave(ctx, req.(*DoSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodFieldService_DoDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodFieldServiceServer).DoDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodFieldService/DoDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodFieldServiceServer).DoDelete(ctx, req.(*DoDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommunicationMethodFieldService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CommunicationMethodFieldService",
	HandlerType: (*CommunicationMethodFieldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoRead",
			Handler:    _CommunicationMethodFieldService_DoRead_Handler,
		},
		{
			MethodName: "DoReadAll",
			Handler:    _CommunicationMethodFieldService_DoReadAll_Handler,
		},
		{
			MethodName: "DoSave",
			Handler:    _CommunicationMethodFieldService_DoSave_Handler,
		},
		{
			MethodName: "DoDelete",
			Handler:    _CommunicationMethodFieldService_DoDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communicationmethodfield.proto",
}
