// Code generated by protoc-gen-go. DO NOT EDIT.
// source: communicationmethodfield.proto

package communicationmethodfield

import (
	context "context"
	fmt "fmt"
	audit "github.com/bungysheep/contact-management/pkg/api/v1/audit"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommunicationMethodField struct {
	ContactSystemCode       string       `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string       `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	FieldCode               string       `protobuf:"bytes,3,opt,name=field_code,json=fieldCode,proto3" json:"field_code,omitempty"`
	Caption                 string       `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	Sequence                int64        `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Audit                   *audit.Audit `protobuf:"bytes,6,opt,name=audit,proto3" json:"audit,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}     `json:"-"`
	XXX_unrecognized        []byte       `json:"-"`
	XXX_sizecache           int32        `json:"-"`
}

func (m *CommunicationMethodField) Reset()         { *m = CommunicationMethodField{} }
func (m *CommunicationMethodField) String() string { return proto.CompactTextString(m) }
func (*CommunicationMethodField) ProtoMessage()    {}
func (*CommunicationMethodField) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{0}
}

func (m *CommunicationMethodField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunicationMethodField.Unmarshal(m, b)
}
func (m *CommunicationMethodField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunicationMethodField.Marshal(b, m, deterministic)
}
func (m *CommunicationMethodField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunicationMethodField.Merge(m, src)
}
func (m *CommunicationMethodField) XXX_Size() int {
	return xxx_messageInfo_CommunicationMethodField.Size(m)
}
func (m *CommunicationMethodField) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunicationMethodField.DiscardUnknown(m)
}

var xxx_messageInfo_CommunicationMethodField proto.InternalMessageInfo

func (m *CommunicationMethodField) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *CommunicationMethodField) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

func (m *CommunicationMethodField) GetFieldCode() string {
	if m != nil {
		return m.FieldCode
	}
	return ""
}

func (m *CommunicationMethodField) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *CommunicationMethodField) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *CommunicationMethodField) GetAudit() *audit.Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

type DoReadCommunicationMethodFieldRequest struct {
	ContactSystemCode       string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	FieldCode               string   `protobuf:"bytes,3,opt,name=field_code,json=fieldCode,proto3" json:"field_code,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DoReadCommunicationMethodFieldRequest) Reset()         { *m = DoReadCommunicationMethodFieldRequest{} }
func (m *DoReadCommunicationMethodFieldRequest) String() string { return proto.CompactTextString(m) }
func (*DoReadCommunicationMethodFieldRequest) ProtoMessage()    {}
func (*DoReadCommunicationMethodFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{1}
}

func (m *DoReadCommunicationMethodFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadCommunicationMethodFieldRequest.Unmarshal(m, b)
}
func (m *DoReadCommunicationMethodFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadCommunicationMethodFieldRequest.Marshal(b, m, deterministic)
}
func (m *DoReadCommunicationMethodFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadCommunicationMethodFieldRequest.Merge(m, src)
}
func (m *DoReadCommunicationMethodFieldRequest) XXX_Size() int {
	return xxx_messageInfo_DoReadCommunicationMethodFieldRequest.Size(m)
}
func (m *DoReadCommunicationMethodFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadCommunicationMethodFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadCommunicationMethodFieldRequest proto.InternalMessageInfo

func (m *DoReadCommunicationMethodFieldRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoReadCommunicationMethodFieldRequest) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

func (m *DoReadCommunicationMethodFieldRequest) GetFieldCode() string {
	if m != nil {
		return m.FieldCode
	}
	return ""
}

type DoReadCommunicationMethodFieldResponse struct {
	CommunicationMethodField *CommunicationMethodField `protobuf:"bytes,1,opt,name=communication_method_field,json=communicationMethodField,proto3" json:"communication_method_field,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *DoReadCommunicationMethodFieldResponse) Reset() {
	*m = DoReadCommunicationMethodFieldResponse{}
}
func (m *DoReadCommunicationMethodFieldResponse) String() string { return proto.CompactTextString(m) }
func (*DoReadCommunicationMethodFieldResponse) ProtoMessage()    {}
func (*DoReadCommunicationMethodFieldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{2}
}

func (m *DoReadCommunicationMethodFieldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadCommunicationMethodFieldResponse.Unmarshal(m, b)
}
func (m *DoReadCommunicationMethodFieldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadCommunicationMethodFieldResponse.Marshal(b, m, deterministic)
}
func (m *DoReadCommunicationMethodFieldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadCommunicationMethodFieldResponse.Merge(m, src)
}
func (m *DoReadCommunicationMethodFieldResponse) XXX_Size() int {
	return xxx_messageInfo_DoReadCommunicationMethodFieldResponse.Size(m)
}
func (m *DoReadCommunicationMethodFieldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadCommunicationMethodFieldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadCommunicationMethodFieldResponse proto.InternalMessageInfo

func (m *DoReadCommunicationMethodFieldResponse) GetCommunicationMethodField() *CommunicationMethodField {
	if m != nil {
		return m.CommunicationMethodField
	}
	return nil
}

type DoReadAllCommunicationMethodFieldRequest struct {
	ContactSystemCode       string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DoReadAllCommunicationMethodFieldRequest) Reset() {
	*m = DoReadAllCommunicationMethodFieldRequest{}
}
func (m *DoReadAllCommunicationMethodFieldRequest) String() string { return proto.CompactTextString(m) }
func (*DoReadAllCommunicationMethodFieldRequest) ProtoMessage()    {}
func (*DoReadAllCommunicationMethodFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{3}
}

func (m *DoReadAllCommunicationMethodFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadAllCommunicationMethodFieldRequest.Unmarshal(m, b)
}
func (m *DoReadAllCommunicationMethodFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadAllCommunicationMethodFieldRequest.Marshal(b, m, deterministic)
}
func (m *DoReadAllCommunicationMethodFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadAllCommunicationMethodFieldRequest.Merge(m, src)
}
func (m *DoReadAllCommunicationMethodFieldRequest) XXX_Size() int {
	return xxx_messageInfo_DoReadAllCommunicationMethodFieldRequest.Size(m)
}
func (m *DoReadAllCommunicationMethodFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadAllCommunicationMethodFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadAllCommunicationMethodFieldRequest proto.InternalMessageInfo

func (m *DoReadAllCommunicationMethodFieldRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoReadAllCommunicationMethodFieldRequest) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

type DoReadAllCommunicationMethodFieldResponse struct {
	CommunicationMethodField []*CommunicationMethodField `protobuf:"bytes,1,rep,name=communication_method_field,json=communicationMethodField,proto3" json:"communication_method_field,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                    `json:"-"`
	XXX_unrecognized         []byte                      `json:"-"`
	XXX_sizecache            int32                       `json:"-"`
}

func (m *DoReadAllCommunicationMethodFieldResponse) Reset() {
	*m = DoReadAllCommunicationMethodFieldResponse{}
}
func (m *DoReadAllCommunicationMethodFieldResponse) String() string { return proto.CompactTextString(m) }
func (*DoReadAllCommunicationMethodFieldResponse) ProtoMessage()    {}
func (*DoReadAllCommunicationMethodFieldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{4}
}

func (m *DoReadAllCommunicationMethodFieldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadAllCommunicationMethodFieldResponse.Unmarshal(m, b)
}
func (m *DoReadAllCommunicationMethodFieldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadAllCommunicationMethodFieldResponse.Marshal(b, m, deterministic)
}
func (m *DoReadAllCommunicationMethodFieldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadAllCommunicationMethodFieldResponse.Merge(m, src)
}
func (m *DoReadAllCommunicationMethodFieldResponse) XXX_Size() int {
	return xxx_messageInfo_DoReadAllCommunicationMethodFieldResponse.Size(m)
}
func (m *DoReadAllCommunicationMethodFieldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadAllCommunicationMethodFieldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadAllCommunicationMethodFieldResponse proto.InternalMessageInfo

func (m *DoReadAllCommunicationMethodFieldResponse) GetCommunicationMethodField() []*CommunicationMethodField {
	if m != nil {
		return m.CommunicationMethodField
	}
	return nil
}

type DoSaveCommunicationMethodFieldRequest struct {
	CommunicationMethodField *CommunicationMethodField `protobuf:"bytes,1,opt,name=communication_method_field,json=communicationMethodField,proto3" json:"communication_method_field,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *DoSaveCommunicationMethodFieldRequest) Reset()         { *m = DoSaveCommunicationMethodFieldRequest{} }
func (m *DoSaveCommunicationMethodFieldRequest) String() string { return proto.CompactTextString(m) }
func (*DoSaveCommunicationMethodFieldRequest) ProtoMessage()    {}
func (*DoSaveCommunicationMethodFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{5}
}

func (m *DoSaveCommunicationMethodFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSaveCommunicationMethodFieldRequest.Unmarshal(m, b)
}
func (m *DoSaveCommunicationMethodFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSaveCommunicationMethodFieldRequest.Marshal(b, m, deterministic)
}
func (m *DoSaveCommunicationMethodFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSaveCommunicationMethodFieldRequest.Merge(m, src)
}
func (m *DoSaveCommunicationMethodFieldRequest) XXX_Size() int {
	return xxx_messageInfo_DoSaveCommunicationMethodFieldRequest.Size(m)
}
func (m *DoSaveCommunicationMethodFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSaveCommunicationMethodFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoSaveCommunicationMethodFieldRequest proto.InternalMessageInfo

func (m *DoSaveCommunicationMethodFieldRequest) GetCommunicationMethodField() *CommunicationMethodField {
	if m != nil {
		return m.CommunicationMethodField
	}
	return nil
}

type DoSaveCommunicationMethodFieldResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoSaveCommunicationMethodFieldResponse) Reset() {
	*m = DoSaveCommunicationMethodFieldResponse{}
}
func (m *DoSaveCommunicationMethodFieldResponse) String() string { return proto.CompactTextString(m) }
func (*DoSaveCommunicationMethodFieldResponse) ProtoMessage()    {}
func (*DoSaveCommunicationMethodFieldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{6}
}

func (m *DoSaveCommunicationMethodFieldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSaveCommunicationMethodFieldResponse.Unmarshal(m, b)
}
func (m *DoSaveCommunicationMethodFieldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSaveCommunicationMethodFieldResponse.Marshal(b, m, deterministic)
}
func (m *DoSaveCommunicationMethodFieldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSaveCommunicationMethodFieldResponse.Merge(m, src)
}
func (m *DoSaveCommunicationMethodFieldResponse) XXX_Size() int {
	return xxx_messageInfo_DoSaveCommunicationMethodFieldResponse.Size(m)
}
func (m *DoSaveCommunicationMethodFieldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSaveCommunicationMethodFieldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoSaveCommunicationMethodFieldResponse proto.InternalMessageInfo

func (m *DoSaveCommunicationMethodFieldResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type DoDeleteCommunicationMethodFieldRequest struct {
	ContactSystemCode       string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	FieldCode               string   `protobuf:"bytes,3,opt,name=field_code,json=fieldCode,proto3" json:"field_code,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DoDeleteCommunicationMethodFieldRequest) Reset() {
	*m = DoDeleteCommunicationMethodFieldRequest{}
}
func (m *DoDeleteCommunicationMethodFieldRequest) String() string { return proto.CompactTextString(m) }
func (*DoDeleteCommunicationMethodFieldRequest) ProtoMessage()    {}
func (*DoDeleteCommunicationMethodFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{7}
}

func (m *DoDeleteCommunicationMethodFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoDeleteCommunicationMethodFieldRequest.Unmarshal(m, b)
}
func (m *DoDeleteCommunicationMethodFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoDeleteCommunicationMethodFieldRequest.Marshal(b, m, deterministic)
}
func (m *DoDeleteCommunicationMethodFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoDeleteCommunicationMethodFieldRequest.Merge(m, src)
}
func (m *DoDeleteCommunicationMethodFieldRequest) XXX_Size() int {
	return xxx_messageInfo_DoDeleteCommunicationMethodFieldRequest.Size(m)
}
func (m *DoDeleteCommunicationMethodFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoDeleteCommunicationMethodFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoDeleteCommunicationMethodFieldRequest proto.InternalMessageInfo

func (m *DoDeleteCommunicationMethodFieldRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoDeleteCommunicationMethodFieldRequest) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

func (m *DoDeleteCommunicationMethodFieldRequest) GetFieldCode() string {
	if m != nil {
		return m.FieldCode
	}
	return ""
}

type DoDeleteCommunicationMethodFieldResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoDeleteCommunicationMethodFieldResponse) Reset() {
	*m = DoDeleteCommunicationMethodFieldResponse{}
}
func (m *DoDeleteCommunicationMethodFieldResponse) String() string { return proto.CompactTextString(m) }
func (*DoDeleteCommunicationMethodFieldResponse) ProtoMessage()    {}
func (*DoDeleteCommunicationMethodFieldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca2fbec7e6e1de, []int{8}
}

func (m *DoDeleteCommunicationMethodFieldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoDeleteCommunicationMethodFieldResponse.Unmarshal(m, b)
}
func (m *DoDeleteCommunicationMethodFieldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoDeleteCommunicationMethodFieldResponse.Marshal(b, m, deterministic)
}
func (m *DoDeleteCommunicationMethodFieldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoDeleteCommunicationMethodFieldResponse.Merge(m, src)
}
func (m *DoDeleteCommunicationMethodFieldResponse) XXX_Size() int {
	return xxx_messageInfo_DoDeleteCommunicationMethodFieldResponse.Size(m)
}
func (m *DoDeleteCommunicationMethodFieldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoDeleteCommunicationMethodFieldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoDeleteCommunicationMethodFieldResponse proto.InternalMessageInfo

func (m *DoDeleteCommunicationMethodFieldResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*CommunicationMethodField)(nil), "v1.CommunicationMethodField")
	proto.RegisterType((*DoReadCommunicationMethodFieldRequest)(nil), "v1.DoReadCommunicationMethodFieldRequest")
	proto.RegisterType((*DoReadCommunicationMethodFieldResponse)(nil), "v1.DoReadCommunicationMethodFieldResponse")
	proto.RegisterType((*DoReadAllCommunicationMethodFieldRequest)(nil), "v1.DoReadAllCommunicationMethodFieldRequest")
	proto.RegisterType((*DoReadAllCommunicationMethodFieldResponse)(nil), "v1.DoReadAllCommunicationMethodFieldResponse")
	proto.RegisterType((*DoSaveCommunicationMethodFieldRequest)(nil), "v1.DoSaveCommunicationMethodFieldRequest")
	proto.RegisterType((*DoSaveCommunicationMethodFieldResponse)(nil), "v1.DoSaveCommunicationMethodFieldResponse")
	proto.RegisterType((*DoDeleteCommunicationMethodFieldRequest)(nil), "v1.DoDeleteCommunicationMethodFieldRequest")
	proto.RegisterType((*DoDeleteCommunicationMethodFieldResponse)(nil), "v1.DoDeleteCommunicationMethodFieldResponse")
}

func init() { proto.RegisterFile("communicationmethodfield.proto", fileDescriptor_17ca2fbec7e6e1de) }

var fileDescriptor_17ca2fbec7e6e1de = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xd5, 0x36, 0x34, 0x24, 0x93, 0x13, 0x8b, 0x04, 0xc6, 0x02, 0x1a, 0x59, 0x02, 0x52, 0x68,
	0x6d, 0x25, 0xdc, 0x38, 0xd1, 0x36, 0xe2, 0x04, 0x1c, 0x9c, 0x5b, 0x2f, 0xd1, 0x66, 0x3d, 0x24,
	0x16, 0xb6, 0xd7, 0x64, 0xd7, 0x96, 0x7a, 0x06, 0x89, 0x3f, 0xe0, 0x43, 0x50, 0x3f, 0x8f, 0x03,
	0xda, 0x5d, 0xa7, 0x80, 0xc0, 0xcd, 0x4a, 0x08, 0x29, 0x1c, 0x77, 0x66, 0xde, 0xce, 0x9b, 0x37,
	0xcf, 0x5e, 0x78, 0xc8, 0x45, 0x9e, 0x57, 0x45, 0xca, 0x99, 0x4a, 0x45, 0x91, 0xa3, 0x5a, 0x89,
	0xe4, 0x5d, 0x8a, 0x59, 0x12, 0x96, 0x6b, 0xa1, 0x04, 0xdd, 0xab, 0xc7, 0xfe, 0x80, 0x55, 0x49,
	0xaa, 0x6c, 0x20, 0xf8, 0x46, 0xc0, 0x3b, 0xfb, 0x19, 0xf3, 0xc6, 0x60, 0x5e, 0x69, 0x0c, 0x0d,
	0xe1, 0x36, 0x17, 0x85, 0x62, 0x5c, 0xcd, 0xe5, 0x85, 0x54, 0x98, 0xcf, 0xb9, 0x48, 0xd0, 0x23,
	0x43, 0x32, 0xea, 0xc7, 0xb7, 0x9a, 0xd4, 0xcc, 0x64, 0xce, 0x44, 0x82, 0xf4, 0x05, 0xdc, 0xfb,
	0xa5, 0xff, 0xdc, 0x12, 0xb0, 0xa8, 0x3d, 0x83, 0xba, 0xcb, 0x7f, 0x6f, 0x66, 0xb0, 0x0f, 0x00,
	0x0c, 0x51, 0x5b, 0xdc, 0x31, 0xc5, 0x7d, 0x13, 0x31, 0x69, 0x0f, 0x6e, 0x72, 0x56, 0x6a, 0x8c,
	0x77, 0xc3, 0xe4, 0x36, 0x47, 0xea, 0x43, 0x4f, 0xe2, 0x87, 0x0a, 0x0b, 0x8e, 0xde, 0xfe, 0x90,
	0x8c, 0x3a, 0xf1, 0xd5, 0x99, 0x1e, 0xc0, 0xbe, 0x19, 0xd6, 0xeb, 0x0e, 0xc9, 0x68, 0x30, 0xe9,
	0x87, 0xf5, 0x38, 0x3c, 0xd1, 0x81, 0xd8, 0xc6, 0x83, 0xaf, 0x04, 0x1e, 0x4d, 0x45, 0x8c, 0x2c,
	0x69, 0x13, 0x21, 0xd6, 0x77, 0x49, 0xb5, 0x43, 0x5a, 0x04, 0x9f, 0x08, 0x3c, 0xde, 0x46, 0x5a,
	0x96, 0xa2, 0x90, 0x48, 0xcf, 0xc1, 0xff, 0x23, 0x0b, 0x73, 0x99, 0x21, 0x3f, 0x98, 0xdc, 0xd7,
	0xaa, 0xb4, 0xde, 0xe4, 0xf1, 0x96, 0x4c, 0xf0, 0x85, 0xc0, 0xc8, 0xd2, 0x38, 0xc9, 0xb2, 0x1d,
	0x92, 0x2f, 0xf8, 0x4c, 0xe0, 0xd0, 0x81, 0x98, 0xa3, 0x44, 0x9d, 0xbf, 0x90, 0xe8, 0xa3, 0xb1,
	0xd7, 0x8c, 0xd5, 0xb8, 0x4d, 0x9f, 0x7f, 0xb9, 0xa8, 0x97, 0xda, 0x2e, 0xd7, 0x93, 0x68, 0xb4,
	0xb8, 0x03, 0xdd, 0x35, 0xca, 0x2a, 0x53, 0xa6, 0x63, 0x2f, 0x6e, 0x4e, 0xc1, 0x25, 0x81, 0x27,
	0x53, 0x31, 0xc5, 0x0c, 0x15, 0xfe, 0x47, 0x1f, 0xca, 0xa9, 0x36, 0xe8, 0x36, 0xd6, 0xd7, 0x8f,
	0x3e, 0xb9, 0xec, 0xc0, 0x41, 0x1b, 0x78, 0x86, 0xeb, 0x3a, 0xe5, 0x48, 0xe7, 0xd0, 0xb5, 0x7e,
	0xa3, 0x87, 0x7a, 0x45, 0x4e, 0x3f, 0x14, 0xff, 0xa9, 0x4b, 0x69, 0x43, 0x6e, 0x05, 0xfd, 0x2b,
	0x43, 0xd3, 0xa3, 0x1f, 0xc0, 0xed, 0x1f, 0x9e, 0x7f, 0xec, 0x58, 0xdd, 0x74, 0x32, 0xa3, 0x68,
	0xaf, 0x6c, 0x46, 0x71, 0x30, 0xef, 0x66, 0x14, 0x27, 0x8b, 0x21, 0xf4, 0x36, 0x3b, 0xa1, 0xcf,
	0x2c, 0xce, 0xc9, 0x57, 0xfe, 0x91, 0x5b, 0xb1, 0x6d, 0x73, 0xfa, 0xf6, 0xfc, 0xf5, 0x32, 0x55,
	0xab, 0x6a, 0x11, 0x72, 0x91, 0x47, 0x8b, 0xaa, 0x58, 0x5e, 0xc8, 0x15, 0x62, 0x19, 0x35, 0x06,
	0x3c, 0xce, 0x59, 0xc1, 0x96, 0x98, 0x63, 0xa1, 0xa2, 0xf2, 0xfd, 0x32, 0x62, 0x65, 0x1a, 0xd5,
	0xe3, 0xa8, 0xed, 0xf9, 0x5c, 0x74, 0xcd, 0x73, 0xf9, 0xfc, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x0c, 0x19, 0x2e, 0xd9, 0x61, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommunicationMethodFieldServiceClient is the client API for CommunicationMethodFieldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommunicationMethodFieldServiceClient interface {
	DoRead(ctx context.Context, in *DoReadCommunicationMethodFieldRequest, opts ...grpc.CallOption) (*DoReadCommunicationMethodFieldResponse, error)
	DoReadAll(ctx context.Context, in *DoReadAllCommunicationMethodFieldRequest, opts ...grpc.CallOption) (*DoReadAllCommunicationMethodFieldResponse, error)
	DoSave(ctx context.Context, in *DoSaveCommunicationMethodFieldRequest, opts ...grpc.CallOption) (*DoSaveCommunicationMethodFieldResponse, error)
	DoDelete(ctx context.Context, in *DoDeleteCommunicationMethodFieldRequest, opts ...grpc.CallOption) (*DoDeleteCommunicationMethodFieldResponse, error)
}

type communicationMethodFieldServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommunicationMethodFieldServiceClient(cc *grpc.ClientConn) CommunicationMethodFieldServiceClient {
	return &communicationMethodFieldServiceClient{cc}
}

func (c *communicationMethodFieldServiceClient) DoRead(ctx context.Context, in *DoReadCommunicationMethodFieldRequest, opts ...grpc.CallOption) (*DoReadCommunicationMethodFieldResponse, error) {
	out := new(DoReadCommunicationMethodFieldResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodFieldService/DoRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodFieldServiceClient) DoReadAll(ctx context.Context, in *DoReadAllCommunicationMethodFieldRequest, opts ...grpc.CallOption) (*DoReadAllCommunicationMethodFieldResponse, error) {
	out := new(DoReadAllCommunicationMethodFieldResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodFieldService/DoReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodFieldServiceClient) DoSave(ctx context.Context, in *DoSaveCommunicationMethodFieldRequest, opts ...grpc.CallOption) (*DoSaveCommunicationMethodFieldResponse, error) {
	out := new(DoSaveCommunicationMethodFieldResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodFieldService/DoSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodFieldServiceClient) DoDelete(ctx context.Context, in *DoDeleteCommunicationMethodFieldRequest, opts ...grpc.CallOption) (*DoDeleteCommunicationMethodFieldResponse, error) {
	out := new(DoDeleteCommunicationMethodFieldResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodFieldService/DoDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicationMethodFieldServiceServer is the server API for CommunicationMethodFieldService service.
type CommunicationMethodFieldServiceServer interface {
	DoRead(context.Context, *DoReadCommunicationMethodFieldRequest) (*DoReadCommunicationMethodFieldResponse, error)
	DoReadAll(context.Context, *DoReadAllCommunicationMethodFieldRequest) (*DoReadAllCommunicationMethodFieldResponse, error)
	DoSave(context.Context, *DoSaveCommunicationMethodFieldRequest) (*DoSaveCommunicationMethodFieldResponse, error)
	DoDelete(context.Context, *DoDeleteCommunicationMethodFieldRequest) (*DoDeleteCommunicationMethodFieldResponse, error)
}

// UnimplementedCommunicationMethodFieldServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommunicationMethodFieldServiceServer struct {
}

func (*UnimplementedCommunicationMethodFieldServiceServer) DoRead(ctx context.Context, req *DoReadCommunicationMethodFieldRequest) (*DoReadCommunicationMethodFieldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoRead not implemented")
}
func (*UnimplementedCommunicationMethodFieldServiceServer) DoReadAll(ctx context.Context, req *DoReadAllCommunicationMethodFieldRequest) (*DoReadAllCommunicationMethodFieldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoReadAll not implemented")
}
func (*UnimplementedCommunicationMethodFieldServiceServer) DoSave(ctx context.Context, req *DoSaveCommunicationMethodFieldRequest) (*DoSaveCommunicationMethodFieldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSave not implemented")
}
func (*UnimplementedCommunicationMethodFieldServiceServer) DoDelete(ctx context.Context, req *DoDeleteCommunicationMethodFieldRequest) (*DoDeleteCommunicationMethodFieldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoDelete not implemented")
}

func RegisterCommunicationMethodFieldServiceServer(s *grpc.Server, srv CommunicationMethodFieldServiceServer) {
	s.RegisterService(&_CommunicationMethodFieldService_serviceDesc, srv)
}

func _CommunicationMethodFieldService_DoRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReadCommunicationMethodFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodFieldServiceServer).DoRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodFieldService/DoRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodFieldServiceServer).DoRead(ctx, req.(*DoReadCommunicationMethodFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodFieldService_DoReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReadAllCommunicationMethodFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodFieldServiceServer).DoReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodFieldService/DoReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodFieldServiceServer).DoReadAll(ctx, req.(*DoReadAllCommunicationMethodFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodFieldService_DoSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoSaveCommunicationMethodFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodFieldServiceServer).DoSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodFieldService/DoSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodFieldServiceServer).DoSave(ctx, req.(*DoSaveCommunicationMethodFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodFieldService_DoDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoDeleteCommunicationMethodFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodFieldServiceServer).DoDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodFieldService/DoDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodFieldServiceServer).DoDelete(ctx, req.(*DoDeleteCommunicationMethodFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommunicationMethodFieldService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CommunicationMethodFieldService",
	HandlerType: (*CommunicationMethodFieldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoRead",
			Handler:    _CommunicationMethodFieldService_DoRead_Handler,
		},
		{
			MethodName: "DoReadAll",
			Handler:    _CommunicationMethodFieldService_DoReadAll_Handler,
		},
		{
			MethodName: "DoSave",
			Handler:    _CommunicationMethodFieldService_DoSave_Handler,
		},
		{
			MethodName: "DoDelete",
			Handler:    _CommunicationMethodFieldService_DoDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communicationmethodfield.proto",
}
