// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contactcommunicationmethodfield.proto

package contactcommunicationmethodfield

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContactCommunicationMethodField struct {
	ContactSystemCode            string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	ContactId                    int64    `protobuf:"varint,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	ContactCommunicationMethodId int64    `protobuf:"varint,3,opt,name=contact_communication_method_id,json=contactCommunicationMethodId,proto3" json:"contact_communication_method_id,omitempty"`
	FieldCode                    string   `protobuf:"bytes,4,opt,name=field_code,json=fieldCode,proto3" json:"field_code,omitempty"`
	FieldValue                   string   `protobuf:"bytes,5,opt,name=field_value,json=fieldValue,proto3" json:"field_value,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *ContactCommunicationMethodField) Reset()         { *m = ContactCommunicationMethodField{} }
func (m *ContactCommunicationMethodField) String() string { return proto.CompactTextString(m) }
func (*ContactCommunicationMethodField) ProtoMessage()    {}
func (*ContactCommunicationMethodField) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcf9983a0d68aa46, []int{0}
}

func (m *ContactCommunicationMethodField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactCommunicationMethodField.Unmarshal(m, b)
}
func (m *ContactCommunicationMethodField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactCommunicationMethodField.Marshal(b, m, deterministic)
}
func (m *ContactCommunicationMethodField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactCommunicationMethodField.Merge(m, src)
}
func (m *ContactCommunicationMethodField) XXX_Size() int {
	return xxx_messageInfo_ContactCommunicationMethodField.Size(m)
}
func (m *ContactCommunicationMethodField) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactCommunicationMethodField.DiscardUnknown(m)
}

var xxx_messageInfo_ContactCommunicationMethodField proto.InternalMessageInfo

func (m *ContactCommunicationMethodField) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *ContactCommunicationMethodField) GetContactId() int64 {
	if m != nil {
		return m.ContactId
	}
	return 0
}

func (m *ContactCommunicationMethodField) GetContactCommunicationMethodId() int64 {
	if m != nil {
		return m.ContactCommunicationMethodId
	}
	return 0
}

func (m *ContactCommunicationMethodField) GetFieldCode() string {
	if m != nil {
		return m.FieldCode
	}
	return ""
}

func (m *ContactCommunicationMethodField) GetFieldValue() string {
	if m != nil {
		return m.FieldValue
	}
	return ""
}

func init() {
	proto.RegisterType((*ContactCommunicationMethodField)(nil), "v1.ContactCommunicationMethodField")
}

func init() {
	proto.RegisterFile("contactcommunicationmethodfield.proto", fileDescriptor_bcf9983a0d68aa46)
}

var fileDescriptor_bcf9983a0d68aa46 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0xc9, 0x9d, 0x0a, 0x59, 0x2b, 0x63, 0x93, 0x42, 0xc9, 0x21, 0x08, 0xd7, 0x98, 0xe5,
	0xf0, 0x0d, 0x0c, 0x0a, 0x57, 0xd8, 0xdc, 0xa1, 0x85, 0x4d, 0xd8, 0xec, 0x8e, 0xc9, 0xe2, 0xed,
	0x4e, 0x30, 0x93, 0xc0, 0x3d, 0xb9, 0xad, 0x64, 0x36, 0x01, 0x2d, 0xc4, 0x76, 0xfe, 0xef, 0xdf,
	0xf9, 0x76, 0xc4, 0xad, 0x46, 0x4f, 0x4a, 0x93, 0x46, 0xe7, 0x7a, 0x6f, 0xb5, 0x22, 0x8b, 0xde,
	0x01, 0x35, 0x68, 0xde, 0x2d, 0x1c, 0x4c, 0xde, 0x7e, 0x22, 0x61, 0xb2, 0x18, 0x36, 0x37, 0x5f,
	0x91, 0xc8, 0x8a, 0x40, 0x17, 0x3f, 0xe9, 0x67, 0xa6, 0x9f, 0x46, 0x3a, 0xc9, 0xc5, 0xe5, 0xf4,
	0x60, 0xd9, 0x1d, 0x3b, 0x02, 0x57, 0x6a, 0x34, 0x90, 0x46, 0xab, 0x68, 0x1d, 0xef, 0x2e, 0xa6,
	0x68, 0xcf, 0x49, 0x81, 0x06, 0x92, 0x6b, 0x21, 0x66, 0xde, 0x9a, 0x74, 0xb1, 0x8a, 0xd6, 0xcb,
	0x5d, 0x3c, 0x4d, 0xb6, 0x26, 0x79, 0x14, 0xd9, 0x1c, 0xff, 0x12, 0x2c, 0x83, 0xe1, 0xd8, 0x59,
	0x72, 0xe7, 0x4a, 0xff, 0x29, 0xb6, 0x35, 0xe3, 0x16, 0xfe, 0x4c, 0x90, 0x39, 0x61, 0x99, 0x98,
	0x27, 0x2c, 0x91, 0x89, 0xf3, 0x10, 0x0f, 0xea, 0xd0, 0x43, 0x7a, 0xca, 0x79, 0x68, 0xbc, 0x8e,
	0x93, 0x87, 0x97, 0xb7, 0x7d, 0x6d, 0xa9, 0xe9, 0xab, 0x5c, 0xa3, 0x93, 0x55, 0xef, 0xeb, 0x63,
	0xd7, 0x00, 0xb4, 0x72, 0xda, 0x7a, 0xe7, 0x94, 0x57, 0x35, 0x38, 0xf0, 0x24, 0xdb, 0x8f, 0x5a,
	0xaa, 0xd6, 0xca, 0x61, 0x23, 0xff, 0x39, 0x6d, 0x75, 0xc6, 0xb7, 0xbd, 0xff, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x2b, 0xed, 0x30, 0xcd, 0x84, 0x01, 0x00, 0x00,
}
