sudo: required

branches:
  only:
  - master

env:
  global:
  - IMG_VERS=$(git rev-parse HEAD)

services:
- docker

before_install:
# Build test image
- docker build -t jamese/contact-management-test .

script:
# Run unit test
- docker run jamese/contact-management-test go test -tags dev -short -v ./...

after_success:
# Build images
- docker build -t jamese/contact-management:latest -t jamese/contact-management:$IMG_VERS .
# Login to docker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push latest image to docker hub
- docker push jamese/contact-management:latest
# Push unique image to docker hub
- docker push jamese/contact-management:$IMG_VERS