// Code generated by protoc-gen-go. DO NOT EDIT.
// source: communicationmethod.proto

package communicationmethod

import (
	context "context"
	fmt "fmt"
	audit "github.com/bungysheep/contact-management/pkg/api/v1/audit"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommunicationMethod struct {
	ContactSystemCode       string       `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string       `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	Description             string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Details                 string       `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Status                  string       `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	FormatField             string       `protobuf:"bytes,6,opt,name=format_field,json=formatField,proto3" json:"format_field,omitempty"`
	Audit                   *audit.Audit `protobuf:"bytes,7,opt,name=audit,proto3" json:"audit,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}     `json:"-"`
	XXX_unrecognized        []byte       `json:"-"`
	XXX_sizecache           int32        `json:"-"`
}

func (m *CommunicationMethod) Reset()         { *m = CommunicationMethod{} }
func (m *CommunicationMethod) String() string { return proto.CompactTextString(m) }
func (*CommunicationMethod) ProtoMessage()    {}
func (*CommunicationMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_66652c2f80ceae65, []int{0}
}

func (m *CommunicationMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunicationMethod.Unmarshal(m, b)
}
func (m *CommunicationMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunicationMethod.Marshal(b, m, deterministic)
}
func (m *CommunicationMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunicationMethod.Merge(m, src)
}
func (m *CommunicationMethod) XXX_Size() int {
	return xxx_messageInfo_CommunicationMethod.Size(m)
}
func (m *CommunicationMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunicationMethod.DiscardUnknown(m)
}

var xxx_messageInfo_CommunicationMethod proto.InternalMessageInfo

func (m *CommunicationMethod) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *CommunicationMethod) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

func (m *CommunicationMethod) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CommunicationMethod) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *CommunicationMethod) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CommunicationMethod) GetFormatField() string {
	if m != nil {
		return m.FormatField
	}
	return ""
}

func (m *CommunicationMethod) GetAudit() *audit.Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

type DoReadCommunicationMethodRequest struct {
	ContactSystemCode       string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DoReadCommunicationMethodRequest) Reset()         { *m = DoReadCommunicationMethodRequest{} }
func (m *DoReadCommunicationMethodRequest) String() string { return proto.CompactTextString(m) }
func (*DoReadCommunicationMethodRequest) ProtoMessage()    {}
func (*DoReadCommunicationMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66652c2f80ceae65, []int{1}
}

func (m *DoReadCommunicationMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadCommunicationMethodRequest.Unmarshal(m, b)
}
func (m *DoReadCommunicationMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadCommunicationMethodRequest.Marshal(b, m, deterministic)
}
func (m *DoReadCommunicationMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadCommunicationMethodRequest.Merge(m, src)
}
func (m *DoReadCommunicationMethodRequest) XXX_Size() int {
	return xxx_messageInfo_DoReadCommunicationMethodRequest.Size(m)
}
func (m *DoReadCommunicationMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadCommunicationMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadCommunicationMethodRequest proto.InternalMessageInfo

func (m *DoReadCommunicationMethodRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoReadCommunicationMethodRequest) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

type DoReadCommunicationMethodResponse struct {
	CommunicationMethod  *CommunicationMethod `protobuf:"bytes,1,opt,name=communication_method,json=communicationMethod,proto3" json:"communication_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DoReadCommunicationMethodResponse) Reset()         { *m = DoReadCommunicationMethodResponse{} }
func (m *DoReadCommunicationMethodResponse) String() string { return proto.CompactTextString(m) }
func (*DoReadCommunicationMethodResponse) ProtoMessage()    {}
func (*DoReadCommunicationMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66652c2f80ceae65, []int{2}
}

func (m *DoReadCommunicationMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadCommunicationMethodResponse.Unmarshal(m, b)
}
func (m *DoReadCommunicationMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadCommunicationMethodResponse.Marshal(b, m, deterministic)
}
func (m *DoReadCommunicationMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadCommunicationMethodResponse.Merge(m, src)
}
func (m *DoReadCommunicationMethodResponse) XXX_Size() int {
	return xxx_messageInfo_DoReadCommunicationMethodResponse.Size(m)
}
func (m *DoReadCommunicationMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadCommunicationMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadCommunicationMethodResponse proto.InternalMessageInfo

func (m *DoReadCommunicationMethodResponse) GetCommunicationMethod() *CommunicationMethod {
	if m != nil {
		return m.CommunicationMethod
	}
	return nil
}

type DoReadAllCommunicationMethodRequest struct {
	ContactSystemCode    string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoReadAllCommunicationMethodRequest) Reset()         { *m = DoReadAllCommunicationMethodRequest{} }
func (m *DoReadAllCommunicationMethodRequest) String() string { return proto.CompactTextString(m) }
func (*DoReadAllCommunicationMethodRequest) ProtoMessage()    {}
func (*DoReadAllCommunicationMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66652c2f80ceae65, []int{3}
}

func (m *DoReadAllCommunicationMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadAllCommunicationMethodRequest.Unmarshal(m, b)
}
func (m *DoReadAllCommunicationMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadAllCommunicationMethodRequest.Marshal(b, m, deterministic)
}
func (m *DoReadAllCommunicationMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadAllCommunicationMethodRequest.Merge(m, src)
}
func (m *DoReadAllCommunicationMethodRequest) XXX_Size() int {
	return xxx_messageInfo_DoReadAllCommunicationMethodRequest.Size(m)
}
func (m *DoReadAllCommunicationMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadAllCommunicationMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadAllCommunicationMethodRequest proto.InternalMessageInfo

func (m *DoReadAllCommunicationMethodRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

type DoReadAllCommunicationMethodResponse struct {
	CommunicationMethod  []*CommunicationMethod `protobuf:"bytes,1,rep,name=communication_method,json=communicationMethod,proto3" json:"communication_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DoReadAllCommunicationMethodResponse) Reset()         { *m = DoReadAllCommunicationMethodResponse{} }
func (m *DoReadAllCommunicationMethodResponse) String() string { return proto.CompactTextString(m) }
func (*DoReadAllCommunicationMethodResponse) ProtoMessage()    {}
func (*DoReadAllCommunicationMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66652c2f80ceae65, []int{4}
}

func (m *DoReadAllCommunicationMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadAllCommunicationMethodResponse.Unmarshal(m, b)
}
func (m *DoReadAllCommunicationMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadAllCommunicationMethodResponse.Marshal(b, m, deterministic)
}
func (m *DoReadAllCommunicationMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadAllCommunicationMethodResponse.Merge(m, src)
}
func (m *DoReadAllCommunicationMethodResponse) XXX_Size() int {
	return xxx_messageInfo_DoReadAllCommunicationMethodResponse.Size(m)
}
func (m *DoReadAllCommunicationMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadAllCommunicationMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadAllCommunicationMethodResponse proto.InternalMessageInfo

func (m *DoReadAllCommunicationMethodResponse) GetCommunicationMethod() []*CommunicationMethod {
	if m != nil {
		return m.CommunicationMethod
	}
	return nil
}

type DoSaveCommunicationMethodRequest struct {
	CommunicationMethod  *CommunicationMethod `protobuf:"bytes,1,opt,name=communication_method,json=communicationMethod,proto3" json:"communication_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DoSaveCommunicationMethodRequest) Reset()         { *m = DoSaveCommunicationMethodRequest{} }
func (m *DoSaveCommunicationMethodRequest) String() string { return proto.CompactTextString(m) }
func (*DoSaveCommunicationMethodRequest) ProtoMessage()    {}
func (*DoSaveCommunicationMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66652c2f80ceae65, []int{5}
}

func (m *DoSaveCommunicationMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSaveCommunicationMethodRequest.Unmarshal(m, b)
}
func (m *DoSaveCommunicationMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSaveCommunicationMethodRequest.Marshal(b, m, deterministic)
}
func (m *DoSaveCommunicationMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSaveCommunicationMethodRequest.Merge(m, src)
}
func (m *DoSaveCommunicationMethodRequest) XXX_Size() int {
	return xxx_messageInfo_DoSaveCommunicationMethodRequest.Size(m)
}
func (m *DoSaveCommunicationMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSaveCommunicationMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoSaveCommunicationMethodRequest proto.InternalMessageInfo

func (m *DoSaveCommunicationMethodRequest) GetCommunicationMethod() *CommunicationMethod {
	if m != nil {
		return m.CommunicationMethod
	}
	return nil
}

type DoSaveCommunicationMethodResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoSaveCommunicationMethodResponse) Reset()         { *m = DoSaveCommunicationMethodResponse{} }
func (m *DoSaveCommunicationMethodResponse) String() string { return proto.CompactTextString(m) }
func (*DoSaveCommunicationMethodResponse) ProtoMessage()    {}
func (*DoSaveCommunicationMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66652c2f80ceae65, []int{6}
}

func (m *DoSaveCommunicationMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSaveCommunicationMethodResponse.Unmarshal(m, b)
}
func (m *DoSaveCommunicationMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSaveCommunicationMethodResponse.Marshal(b, m, deterministic)
}
func (m *DoSaveCommunicationMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSaveCommunicationMethodResponse.Merge(m, src)
}
func (m *DoSaveCommunicationMethodResponse) XXX_Size() int {
	return xxx_messageInfo_DoSaveCommunicationMethodResponse.Size(m)
}
func (m *DoSaveCommunicationMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSaveCommunicationMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoSaveCommunicationMethodResponse proto.InternalMessageInfo

func (m *DoSaveCommunicationMethodResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type DoDeleteCommunicationMethodRequest struct {
	ContactSystemCode       string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DoDeleteCommunicationMethodRequest) Reset()         { *m = DoDeleteCommunicationMethodRequest{} }
func (m *DoDeleteCommunicationMethodRequest) String() string { return proto.CompactTextString(m) }
func (*DoDeleteCommunicationMethodRequest) ProtoMessage()    {}
func (*DoDeleteCommunicationMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66652c2f80ceae65, []int{7}
}

func (m *DoDeleteCommunicationMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoDeleteCommunicationMethodRequest.Unmarshal(m, b)
}
func (m *DoDeleteCommunicationMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoDeleteCommunicationMethodRequest.Marshal(b, m, deterministic)
}
func (m *DoDeleteCommunicationMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoDeleteCommunicationMethodRequest.Merge(m, src)
}
func (m *DoDeleteCommunicationMethodRequest) XXX_Size() int {
	return xxx_messageInfo_DoDeleteCommunicationMethodRequest.Size(m)
}
func (m *DoDeleteCommunicationMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoDeleteCommunicationMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoDeleteCommunicationMethodRequest proto.InternalMessageInfo

func (m *DoDeleteCommunicationMethodRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoDeleteCommunicationMethodRequest) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

type DoDeleteCommunicationMethodResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoDeleteCommunicationMethodResponse) Reset()         { *m = DoDeleteCommunicationMethodResponse{} }
func (m *DoDeleteCommunicationMethodResponse) String() string { return proto.CompactTextString(m) }
func (*DoDeleteCommunicationMethodResponse) ProtoMessage()    {}
func (*DoDeleteCommunicationMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66652c2f80ceae65, []int{8}
}

func (m *DoDeleteCommunicationMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoDeleteCommunicationMethodResponse.Unmarshal(m, b)
}
func (m *DoDeleteCommunicationMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoDeleteCommunicationMethodResponse.Marshal(b, m, deterministic)
}
func (m *DoDeleteCommunicationMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoDeleteCommunicationMethodResponse.Merge(m, src)
}
func (m *DoDeleteCommunicationMethodResponse) XXX_Size() int {
	return xxx_messageInfo_DoDeleteCommunicationMethodResponse.Size(m)
}
func (m *DoDeleteCommunicationMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoDeleteCommunicationMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoDeleteCommunicationMethodResponse proto.InternalMessageInfo

func (m *DoDeleteCommunicationMethodResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*CommunicationMethod)(nil), "v1.CommunicationMethod")
	proto.RegisterType((*DoReadCommunicationMethodRequest)(nil), "v1.DoReadCommunicationMethodRequest")
	proto.RegisterType((*DoReadCommunicationMethodResponse)(nil), "v1.DoReadCommunicationMethodResponse")
	proto.RegisterType((*DoReadAllCommunicationMethodRequest)(nil), "v1.DoReadAllCommunicationMethodRequest")
	proto.RegisterType((*DoReadAllCommunicationMethodResponse)(nil), "v1.DoReadAllCommunicationMethodResponse")
	proto.RegisterType((*DoSaveCommunicationMethodRequest)(nil), "v1.DoSaveCommunicationMethodRequest")
	proto.RegisterType((*DoSaveCommunicationMethodResponse)(nil), "v1.DoSaveCommunicationMethodResponse")
	proto.RegisterType((*DoDeleteCommunicationMethodRequest)(nil), "v1.DoDeleteCommunicationMethodRequest")
	proto.RegisterType((*DoDeleteCommunicationMethodResponse)(nil), "v1.DoDeleteCommunicationMethodResponse")
}

func init() { proto.RegisterFile("communicationmethod.proto", fileDescriptor_66652c2f80ceae65) }

var fileDescriptor_66652c2f80ceae65 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x56, 0x5b, 0x96, 0xad, 0xaf, 0x5c, 0x70, 0xd1, 0x16, 0x72, 0xa1, 0x0b, 0x83, 0xf5, 0x42,
	0xa2, 0x96, 0x1b, 0x88, 0xc3, 0x58, 0x05, 0x02, 0x89, 0x4b, 0xaa, 0x5d, 0x40, 0xa2, 0x72, 0x9d,
	0xb7, 0xd6, 0x22, 0x89, 0x43, 0xec, 0x44, 0xda, 0x2f, 0xe0, 0x86, 0xb8, 0xf2, 0x6f, 0x91, 0xed,
	0x14, 0x26, 0x08, 0x89, 0x90, 0x26, 0xc4, 0xd1, 0xef, 0xbd, 0xcf, 0xdf, 0xf7, 0x3e, 0x7f, 0x51,
	0xe0, 0x1e, 0x13, 0x69, 0x5a, 0x66, 0x9c, 0x51, 0xc5, 0x45, 0x96, 0xa2, 0xda, 0x8a, 0x38, 0xc8,
	0x0b, 0xa1, 0x04, 0xe9, 0x57, 0x33, 0x6f, 0x44, 0xcb, 0x98, 0x2b, 0x5b, 0xf0, 0xbf, 0xf5, 0x61,
	0x7c, 0x7e, 0x7d, 0xfc, 0xad, 0x19, 0x27, 0x01, 0x8c, 0x99, 0xc8, 0x14, 0x65, 0x6a, 0x25, 0xaf,
	0xa4, 0xc2, 0x74, 0xc5, 0x44, 0x8c, 0x6e, 0x6f, 0xd2, 0x9b, 0x0e, 0xa3, 0x3b, 0x75, 0x6b, 0x69,
	0x3a, 0xe7, 0x22, 0x46, 0xf2, 0xf4, 0x17, 0xd6, 0x95, 0xa5, 0xb5, 0xa8, 0xbe, 0x41, 0x1d, 0xb1,
	0xdf, 0x79, 0x0c, 0x76, 0x02, 0xa3, 0x18, 0x25, 0x2b, 0x78, 0xae, 0x1b, 0xee, 0xc0, 0x4c, 0x5f,
	0x2f, 0x11, 0x17, 0xf6, 0x63, 0x54, 0x94, 0x27, 0xd2, 0xbd, 0x65, 0xba, 0xbb, 0x23, 0x39, 0x04,
	0x47, 0x2a, 0xaa, 0x4a, 0xe9, 0xee, 0x99, 0x46, 0x7d, 0x22, 0xc7, 0x70, 0xfb, 0x52, 0x14, 0x29,
	0x55, 0xab, 0x4b, 0x8e, 0x49, 0xec, 0x3a, 0xf6, 0x52, 0x5b, 0x7b, 0xa9, 0x4b, 0xe4, 0x3e, 0xec,
	0x19, 0x27, 0xdc, 0xfd, 0x49, 0x6f, 0x3a, 0x9a, 0x0f, 0x83, 0x6a, 0x16, 0x9c, 0xe9, 0x42, 0x64,
	0xeb, 0xfe, 0x97, 0x1e, 0x4c, 0x16, 0x22, 0x42, 0x1a, 0x37, 0x38, 0x14, 0xe1, 0xa7, 0x12, 0xa5,
	0xfa, 0x97, 0x46, 0xf9, 0x02, 0x8e, 0x5b, 0xf4, 0xc8, 0x5c, 0x64, 0x12, 0xc9, 0x1b, 0xb8, 0xdb,
	0x44, 0x60, 0x14, 0x8d, 0xe6, 0x47, 0x7a, 0xcb, 0x26, 0xf8, 0xb8, 0x81, 0xd4, 0xbf, 0x80, 0x07,
	0x96, 0xf0, 0x2c, 0x49, 0x6e, 0xce, 0x03, 0xbf, 0x80, 0x93, 0xf6, 0x6b, 0x3b, 0x57, 0x19, 0xfc,
	0xf5, 0x2a, 0x99, 0x7e, 0xcb, 0x25, 0xad, 0xb0, 0x65, 0x8f, 0x9b, 0xb4, 0xee, 0x99, 0x7e, 0xab,
	0x3f, 0xf2, 0xd5, 0x0b, 0x1e, 0x82, 0x53, 0xa0, 0x2c, 0x13, 0x65, 0x28, 0x0e, 0xa2, 0xfa, 0xe4,
	0x7f, 0xed, 0x81, 0xbf, 0x10, 0x0b, 0x4c, 0x50, 0xe1, 0x7f, 0x92, 0xbd, 0xe7, 0x3a, 0x0a, 0x2d,
	0x8a, 0xda, 0x37, 0x9a, 0x7f, 0x1e, 0x80, 0xd7, 0x80, 0x5b, 0x62, 0x51, 0x71, 0x86, 0xe4, 0x02,
	0x1c, 0x9b, 0x08, 0x72, 0xa2, 0x5d, 0xee, 0xfa, 0xea, 0xbc, 0x87, 0x1d, 0x53, 0xb5, 0x9a, 0x0f,
	0x30, 0xfc, 0x11, 0x34, 0x72, 0xfa, 0x13, 0xd3, 0x1a, 0x67, 0x6f, 0xda, 0x3d, 0x58, 0xdf, 0x6f,
	0x64, 0xeb, 0x47, 0xde, 0xc9, 0x6e, 0x0f, 0xd8, 0x4e, 0x76, 0x57, 0x2c, 0xde, 0xc3, 0xc1, 0xce,
	0x6b, 0xf2, 0xc8, 0x42, 0xba, 0xb2, 0xe0, 0x9d, 0x76, 0xce, 0xd9, 0xcb, 0x5f, 0xbc, 0x7e, 0xf7,
	0x6a, 0xc3, 0xd5, 0xb6, 0x5c, 0x07, 0x4c, 0xa4, 0xe1, 0xba, 0xcc, 0x36, 0x57, 0x72, 0x8b, 0x98,
	0x87, 0x75, 0x5e, 0x1e, 0xa7, 0x34, 0xa3, 0x1b, 0x4c, 0x31, 0x53, 0x61, 0xfe, 0x71, 0x13, 0xd2,
	0x9c, 0x87, 0xd5, 0x2c, 0x6c, 0xf8, 0xa7, 0xac, 0x1d, 0xf3, 0x0f, 0x79, 0xf2, 0x3d, 0x00, 0x00,
	0xff, 0xff, 0xe8, 0xbc, 0x1a, 0xc9, 0x71, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommunicationMethodServiceClient is the client API for CommunicationMethodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommunicationMethodServiceClient interface {
	DoRead(ctx context.Context, in *DoReadCommunicationMethodRequest, opts ...grpc.CallOption) (*DoReadCommunicationMethodResponse, error)
	DoReadAll(ctx context.Context, in *DoReadAllCommunicationMethodRequest, opts ...grpc.CallOption) (*DoReadAllCommunicationMethodResponse, error)
	DoSave(ctx context.Context, in *DoSaveCommunicationMethodRequest, opts ...grpc.CallOption) (*DoSaveCommunicationMethodResponse, error)
	DoDelete(ctx context.Context, in *DoDeleteCommunicationMethodRequest, opts ...grpc.CallOption) (*DoDeleteCommunicationMethodResponse, error)
}

type communicationMethodServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommunicationMethodServiceClient(cc *grpc.ClientConn) CommunicationMethodServiceClient {
	return &communicationMethodServiceClient{cc}
}

func (c *communicationMethodServiceClient) DoRead(ctx context.Context, in *DoReadCommunicationMethodRequest, opts ...grpc.CallOption) (*DoReadCommunicationMethodResponse, error) {
	out := new(DoReadCommunicationMethodResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodService/DoRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodServiceClient) DoReadAll(ctx context.Context, in *DoReadAllCommunicationMethodRequest, opts ...grpc.CallOption) (*DoReadAllCommunicationMethodResponse, error) {
	out := new(DoReadAllCommunicationMethodResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodService/DoReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodServiceClient) DoSave(ctx context.Context, in *DoSaveCommunicationMethodRequest, opts ...grpc.CallOption) (*DoSaveCommunicationMethodResponse, error) {
	out := new(DoSaveCommunicationMethodResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodService/DoSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodServiceClient) DoDelete(ctx context.Context, in *DoDeleteCommunicationMethodRequest, opts ...grpc.CallOption) (*DoDeleteCommunicationMethodResponse, error) {
	out := new(DoDeleteCommunicationMethodResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodService/DoDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicationMethodServiceServer is the server API for CommunicationMethodService service.
type CommunicationMethodServiceServer interface {
	DoRead(context.Context, *DoReadCommunicationMethodRequest) (*DoReadCommunicationMethodResponse, error)
	DoReadAll(context.Context, *DoReadAllCommunicationMethodRequest) (*DoReadAllCommunicationMethodResponse, error)
	DoSave(context.Context, *DoSaveCommunicationMethodRequest) (*DoSaveCommunicationMethodResponse, error)
	DoDelete(context.Context, *DoDeleteCommunicationMethodRequest) (*DoDeleteCommunicationMethodResponse, error)
}

// UnimplementedCommunicationMethodServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommunicationMethodServiceServer struct {
}

func (*UnimplementedCommunicationMethodServiceServer) DoRead(ctx context.Context, req *DoReadCommunicationMethodRequest) (*DoReadCommunicationMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoRead not implemented")
}
func (*UnimplementedCommunicationMethodServiceServer) DoReadAll(ctx context.Context, req *DoReadAllCommunicationMethodRequest) (*DoReadAllCommunicationMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoReadAll not implemented")
}
func (*UnimplementedCommunicationMethodServiceServer) DoSave(ctx context.Context, req *DoSaveCommunicationMethodRequest) (*DoSaveCommunicationMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSave not implemented")
}
func (*UnimplementedCommunicationMethodServiceServer) DoDelete(ctx context.Context, req *DoDeleteCommunicationMethodRequest) (*DoDeleteCommunicationMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoDelete not implemented")
}

func RegisterCommunicationMethodServiceServer(s *grpc.Server, srv CommunicationMethodServiceServer) {
	s.RegisterService(&_CommunicationMethodService_serviceDesc, srv)
}

func _CommunicationMethodService_DoRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReadCommunicationMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodServiceServer).DoRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodService/DoRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodServiceServer).DoRead(ctx, req.(*DoReadCommunicationMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodService_DoReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReadAllCommunicationMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodServiceServer).DoReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodService/DoReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodServiceServer).DoReadAll(ctx, req.(*DoReadAllCommunicationMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodService_DoSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoSaveCommunicationMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodServiceServer).DoSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodService/DoSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodServiceServer).DoSave(ctx, req.(*DoSaveCommunicationMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodService_DoDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoDeleteCommunicationMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodServiceServer).DoDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodService/DoDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodServiceServer).DoDelete(ctx, req.(*DoDeleteCommunicationMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommunicationMethodService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CommunicationMethodService",
	HandlerType: (*CommunicationMethodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoRead",
			Handler:    _CommunicationMethodService_DoRead_Handler,
		},
		{
			MethodName: "DoReadAll",
			Handler:    _CommunicationMethodService_DoReadAll_Handler,
		},
		{
			MethodName: "DoSave",
			Handler:    _CommunicationMethodService_DoSave_Handler,
		},
		{
			MethodName: "DoDelete",
			Handler:    _CommunicationMethodService_DoDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communicationmethod.proto",
}
