// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contactcommunicationmethod.proto

package contactcommunicationmethod

import (
	context "context"
	fmt "fmt"
	audit "github.com/bungysheep/contact-management/pkg/api/v1/audit"
	contactcommunicationmethodfield "github.com/bungysheep/contact-management/pkg/api/v1/contactcommunicationmethodfield"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContactCommunicationMethod struct {
	ContactSystemCode               string                                                             `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	ContactId                       int64                                                              `protobuf:"varint,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	ContactCommunicationMethodId    int64                                                              `protobuf:"varint,3,opt,name=contact_communication_method_id,json=contactCommunicationMethodId,proto3" json:"contact_communication_method_id,omitempty"`
	CommunicationMethodCode         string                                                             `protobuf:"bytes,4,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	ContactCommunicationMethodField []*contactcommunicationmethodfield.ContactCommunicationMethodField `protobuf:"bytes,5,rep,name=contact_communication_method_field,json=contactCommunicationMethodField,proto3" json:"contact_communication_method_field,omitempty"`
	Audit                           *audit.Audit                                                       `protobuf:"bytes,6,opt,name=audit,proto3" json:"audit,omitempty"`
	XXX_NoUnkeyedLiteral            struct{}                                                           `json:"-"`
	XXX_unrecognized                []byte                                                             `json:"-"`
	XXX_sizecache                   int32                                                              `json:"-"`
}

func (m *ContactCommunicationMethod) Reset()         { *m = ContactCommunicationMethod{} }
func (m *ContactCommunicationMethod) String() string { return proto.CompactTextString(m) }
func (*ContactCommunicationMethod) ProtoMessage()    {}
func (*ContactCommunicationMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e73ba28293f485, []int{0}
}

func (m *ContactCommunicationMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactCommunicationMethod.Unmarshal(m, b)
}
func (m *ContactCommunicationMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactCommunicationMethod.Marshal(b, m, deterministic)
}
func (m *ContactCommunicationMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactCommunicationMethod.Merge(m, src)
}
func (m *ContactCommunicationMethod) XXX_Size() int {
	return xxx_messageInfo_ContactCommunicationMethod.Size(m)
}
func (m *ContactCommunicationMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactCommunicationMethod.DiscardUnknown(m)
}

var xxx_messageInfo_ContactCommunicationMethod proto.InternalMessageInfo

func (m *ContactCommunicationMethod) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *ContactCommunicationMethod) GetContactId() int64 {
	if m != nil {
		return m.ContactId
	}
	return 0
}

func (m *ContactCommunicationMethod) GetContactCommunicationMethodId() int64 {
	if m != nil {
		return m.ContactCommunicationMethodId
	}
	return 0
}

func (m *ContactCommunicationMethod) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

func (m *ContactCommunicationMethod) GetContactCommunicationMethodField() []*contactcommunicationmethodfield.ContactCommunicationMethodField {
	if m != nil {
		return m.ContactCommunicationMethodField
	}
	return nil
}

func (m *ContactCommunicationMethod) GetAudit() *audit.Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

type DoReadRequest struct {
	ContactSystemCode            string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	ContactId                    int64    `protobuf:"varint,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	ContactCommunicationMethodId int64    `protobuf:"varint,3,opt,name=contact_communication_method_id,json=contactCommunicationMethodId,proto3" json:"contact_communication_method_id,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *DoReadRequest) Reset()         { *m = DoReadRequest{} }
func (m *DoReadRequest) String() string { return proto.CompactTextString(m) }
func (*DoReadRequest) ProtoMessage()    {}
func (*DoReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e73ba28293f485, []int{1}
}

func (m *DoReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadRequest.Unmarshal(m, b)
}
func (m *DoReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadRequest.Marshal(b, m, deterministic)
}
func (m *DoReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadRequest.Merge(m, src)
}
func (m *DoReadRequest) XXX_Size() int {
	return xxx_messageInfo_DoReadRequest.Size(m)
}
func (m *DoReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadRequest proto.InternalMessageInfo

func (m *DoReadRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoReadRequest) GetContactId() int64 {
	if m != nil {
		return m.ContactId
	}
	return 0
}

func (m *DoReadRequest) GetContactCommunicationMethodId() int64 {
	if m != nil {
		return m.ContactCommunicationMethodId
	}
	return 0
}

type DoReadResponse struct {
	ContactCommunicationMethod *ContactCommunicationMethod `protobuf:"bytes,1,opt,name=contact_communication_method,json=contactCommunicationMethod,proto3" json:"contact_communication_method,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                    `json:"-"`
	XXX_unrecognized           []byte                      `json:"-"`
	XXX_sizecache              int32                       `json:"-"`
}

func (m *DoReadResponse) Reset()         { *m = DoReadResponse{} }
func (m *DoReadResponse) String() string { return proto.CompactTextString(m) }
func (*DoReadResponse) ProtoMessage()    {}
func (*DoReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e73ba28293f485, []int{2}
}

func (m *DoReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadResponse.Unmarshal(m, b)
}
func (m *DoReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadResponse.Marshal(b, m, deterministic)
}
func (m *DoReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadResponse.Merge(m, src)
}
func (m *DoReadResponse) XXX_Size() int {
	return xxx_messageInfo_DoReadResponse.Size(m)
}
func (m *DoReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadResponse proto.InternalMessageInfo

func (m *DoReadResponse) GetContactCommunicationMethod() *ContactCommunicationMethod {
	if m != nil {
		return m.ContactCommunicationMethod
	}
	return nil
}

type DoReadAllRequest struct {
	ContactSystemCode    string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoReadAllRequest) Reset()         { *m = DoReadAllRequest{} }
func (m *DoReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*DoReadAllRequest) ProtoMessage()    {}
func (*DoReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e73ba28293f485, []int{3}
}

func (m *DoReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadAllRequest.Unmarshal(m, b)
}
func (m *DoReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadAllRequest.Marshal(b, m, deterministic)
}
func (m *DoReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadAllRequest.Merge(m, src)
}
func (m *DoReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_DoReadAllRequest.Size(m)
}
func (m *DoReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadAllRequest proto.InternalMessageInfo

func (m *DoReadAllRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

type DoReadAllResponse struct {
	ContactCommunicationMethod []*ContactCommunicationMethod `protobuf:"bytes,1,rep,name=contact_communication_method,json=contactCommunicationMethod,proto3" json:"contact_communication_method,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                      `json:"-"`
	XXX_unrecognized           []byte                        `json:"-"`
	XXX_sizecache              int32                         `json:"-"`
}

func (m *DoReadAllResponse) Reset()         { *m = DoReadAllResponse{} }
func (m *DoReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*DoReadAllResponse) ProtoMessage()    {}
func (*DoReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e73ba28293f485, []int{4}
}

func (m *DoReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadAllResponse.Unmarshal(m, b)
}
func (m *DoReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadAllResponse.Marshal(b, m, deterministic)
}
func (m *DoReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadAllResponse.Merge(m, src)
}
func (m *DoReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_DoReadAllResponse.Size(m)
}
func (m *DoReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadAllResponse proto.InternalMessageInfo

func (m *DoReadAllResponse) GetContactCommunicationMethod() []*ContactCommunicationMethod {
	if m != nil {
		return m.ContactCommunicationMethod
	}
	return nil
}

type DoSaveRequest struct {
	ContactCommunicationMethod *ContactCommunicationMethod `protobuf:"bytes,1,opt,name=contact_communication_method,json=contactCommunicationMethod,proto3" json:"contact_communication_method,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                    `json:"-"`
	XXX_unrecognized           []byte                      `json:"-"`
	XXX_sizecache              int32                       `json:"-"`
}

func (m *DoSaveRequest) Reset()         { *m = DoSaveRequest{} }
func (m *DoSaveRequest) String() string { return proto.CompactTextString(m) }
func (*DoSaveRequest) ProtoMessage()    {}
func (*DoSaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e73ba28293f485, []int{5}
}

func (m *DoSaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSaveRequest.Unmarshal(m, b)
}
func (m *DoSaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSaveRequest.Marshal(b, m, deterministic)
}
func (m *DoSaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSaveRequest.Merge(m, src)
}
func (m *DoSaveRequest) XXX_Size() int {
	return xxx_messageInfo_DoSaveRequest.Size(m)
}
func (m *DoSaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoSaveRequest proto.InternalMessageInfo

func (m *DoSaveRequest) GetContactCommunicationMethod() *ContactCommunicationMethod {
	if m != nil {
		return m.ContactCommunicationMethod
	}
	return nil
}

type DoSaveResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoSaveResponse) Reset()         { *m = DoSaveResponse{} }
func (m *DoSaveResponse) String() string { return proto.CompactTextString(m) }
func (*DoSaveResponse) ProtoMessage()    {}
func (*DoSaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e73ba28293f485, []int{6}
}

func (m *DoSaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSaveResponse.Unmarshal(m, b)
}
func (m *DoSaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSaveResponse.Marshal(b, m, deterministic)
}
func (m *DoSaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSaveResponse.Merge(m, src)
}
func (m *DoSaveResponse) XXX_Size() int {
	return xxx_messageInfo_DoSaveResponse.Size(m)
}
func (m *DoSaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoSaveResponse proto.InternalMessageInfo

func (m *DoSaveResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type DoDeleteRequest struct {
	ContactSystemCode            string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	ContactId                    int64    `protobuf:"varint,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	ContactCommunicationMethodId int64    `protobuf:"varint,3,opt,name=contact_communication_method_id,json=contactCommunicationMethodId,proto3" json:"contact_communication_method_id,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *DoDeleteRequest) Reset()         { *m = DoDeleteRequest{} }
func (m *DoDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DoDeleteRequest) ProtoMessage()    {}
func (*DoDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e73ba28293f485, []int{7}
}

func (m *DoDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoDeleteRequest.Unmarshal(m, b)
}
func (m *DoDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoDeleteRequest.Marshal(b, m, deterministic)
}
func (m *DoDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoDeleteRequest.Merge(m, src)
}
func (m *DoDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DoDeleteRequest.Size(m)
}
func (m *DoDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoDeleteRequest proto.InternalMessageInfo

func (m *DoDeleteRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoDeleteRequest) GetContactId() int64 {
	if m != nil {
		return m.ContactId
	}
	return 0
}

func (m *DoDeleteRequest) GetContactCommunicationMethodId() int64 {
	if m != nil {
		return m.ContactCommunicationMethodId
	}
	return 0
}

type DoDeleteResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoDeleteResponse) Reset()         { *m = DoDeleteResponse{} }
func (m *DoDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DoDeleteResponse) ProtoMessage()    {}
func (*DoDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e73ba28293f485, []int{8}
}

func (m *DoDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoDeleteResponse.Unmarshal(m, b)
}
func (m *DoDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoDeleteResponse.Marshal(b, m, deterministic)
}
func (m *DoDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoDeleteResponse.Merge(m, src)
}
func (m *DoDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DoDeleteResponse.Size(m)
}
func (m *DoDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoDeleteResponse proto.InternalMessageInfo

func (m *DoDeleteResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*ContactCommunicationMethod)(nil), "v1.ContactCommunicationMethod")
	proto.RegisterType((*DoReadRequest)(nil), "v1.DoReadRequest")
	proto.RegisterType((*DoReadResponse)(nil), "v1.DoReadResponse")
	proto.RegisterType((*DoReadAllRequest)(nil), "v1.DoReadAllRequest")
	proto.RegisterType((*DoReadAllResponse)(nil), "v1.DoReadAllResponse")
	proto.RegisterType((*DoSaveRequest)(nil), "v1.DoSaveRequest")
	proto.RegisterType((*DoSaveResponse)(nil), "v1.DoSaveResponse")
	proto.RegisterType((*DoDeleteRequest)(nil), "v1.DoDeleteRequest")
	proto.RegisterType((*DoDeleteResponse)(nil), "v1.DoDeleteResponse")
}

func init() { proto.RegisterFile("contactcommunicationmethod.proto", fileDescriptor_64e73ba28293f485) }

var fileDescriptor_64e73ba28293f485 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x4d, 0x8b, 0xd3, 0x50,
	0x14, 0x25, 0x13, 0xa7, 0x4c, 0x6f, 0xf1, 0xa3, 0x6f, 0x46, 0xad, 0x61, 0xb4, 0x31, 0x22, 0x04,
	0xc1, 0x84, 0x56, 0x04, 0x71, 0x37, 0xd3, 0x2a, 0xcc, 0x42, 0x91, 0x74, 0xe7, 0xa6, 0xa6, 0x2f,
	0xd7, 0x36, 0x98, 0xe4, 0x65, 0x9a, 0x97, 0xc0, 0x2c, 0xfd, 0x31, 0xe2, 0x3f, 0x74, 0x2d, 0xef,
	0x23, 0x4e, 0xa3, 0x26, 0x88, 0x22, 0xcc, 0xb2, 0xf7, 0x9e, 0x73, 0xcf, 0x79, 0xe7, 0xde, 0x12,
	0xb0, 0x29, 0xcb, 0x78, 0x48, 0x39, 0x65, 0x69, 0x5a, 0x66, 0x31, 0x0d, 0x79, 0xcc, 0xb2, 0x14,
	0xf9, 0x86, 0x45, 0x5e, 0xbe, 0x65, 0x9c, 0x91, 0xbd, 0x6a, 0x62, 0x0d, 0xc2, 0x32, 0x8a, 0xb9,
	0x2a, 0x58, 0x8f, 0xdb, 0x29, 0x1f, 0x63, 0x4c, 0x34, 0xcf, 0xf9, 0x6c, 0x82, 0x35, 0x53, 0xc8,
	0xd9, 0x2e, 0xf2, 0x8d, 0x44, 0x12, 0x0f, 0x0e, 0xf5, 0x9c, 0x65, 0x71, 0x51, 0x70, 0x4c, 0x97,
	0x94, 0x45, 0x38, 0x32, 0x6c, 0xc3, 0xed, 0x07, 0x43, 0xdd, 0x5a, 0xc8, 0xce, 0x8c, 0x45, 0x48,
	0xee, 0x03, 0xd4, 0xf8, 0x38, 0x1a, 0xed, 0xd9, 0x86, 0x6b, 0x06, 0x7d, 0x5d, 0x39, 0x8b, 0xc8,
	0x2b, 0x18, 0xd7, 0xed, 0x86, 0xaf, 0xa5, 0x32, 0x26, 0x38, 0xa6, 0xe4, 0x1c, 0xd3, 0x56, 0x4f,
	0x67, 0x11, 0x79, 0x09, 0xf7, 0x7e, 0x4b, 0x97, 0xde, 0xae, 0x49, 0x6f, 0x77, 0xe9, 0xaf, 0x4c,
	0xe9, 0x30, 0x07, 0xa7, 0xd3, 0x82, 0x0c, 0x67, 0xb4, 0x6f, 0x9b, 0xee, 0x60, 0xfa, 0xc8, 0xab,
	0x26, 0x5e, 0x7b, 0x3a, 0xaf, 0x05, 0x34, 0x18, 0xd3, 0x6e, 0x00, 0x19, 0xc3, 0xbe, 0x5c, 0xcc,
	0xa8, 0x67, 0x1b, 0xee, 0x60, 0xda, 0x17, 0x43, 0x4f, 0x44, 0x21, 0x50, 0x75, 0xe7, 0x8b, 0x01,
	0xd7, 0xe7, 0x2c, 0xc0, 0x30, 0x0a, 0xf0, 0xbc, 0xc4, 0x82, 0x5f, 0xcd, 0xd8, 0x9d, 0x2d, 0xdc,
	0xa8, 0x6d, 0x16, 0x39, 0xcb, 0x0a, 0x24, 0x1f, 0xe0, 0xb8, 0x6b, 0xb0, 0x34, 0x3c, 0x98, 0x3e,
	0xe8, 0x8e, 0x31, 0xb0, 0xda, 0x55, 0x9d, 0x53, 0xb8, 0xa5, 0x34, 0x4f, 0x92, 0xe4, 0x2f, 0xd3,
	0x71, 0x4a, 0x18, 0xee, 0xcc, 0xf8, 0x63, 0xeb, 0xe6, 0x3f, 0x5a, 0x3f, 0x17, 0x5b, 0x5d, 0x84,
	0x15, 0xd6, 0xbe, 0xff, 0x7f, 0x5a, 0xae, 0xd8, 0x90, 0x92, 0xd4, 0xcf, 0xbc, 0x03, 0xbd, 0x2d,
	0x16, 0x65, 0xc2, 0xe5, 0xf4, 0x83, 0x40, 0xff, 0x72, 0xbe, 0x1a, 0x70, 0x73, 0xce, 0xe6, 0x98,
	0x20, 0xc7, 0xab, 0x7d, 0x75, 0x4f, 0xc4, 0x05, 0xd4, 0x46, 0xbb, 0x5f, 0x35, 0xfd, 0x66, 0xc0,
	0xc3, 0xf6, 0xe8, 0x16, 0xb8, 0xad, 0x62, 0x8a, 0xc4, 0x87, 0x9e, 0xba, 0x07, 0x32, 0x14, 0x59,
	0x37, 0xfe, 0x7a, 0x16, 0xd9, 0x2d, 0x69, 0xb9, 0x17, 0xd0, 0xff, 0x71, 0x40, 0xe4, 0xe8, 0x12,
	0x70, 0x79, 0x93, 0xd6, 0xed, 0x9f, 0xaa, 0x9a, 0x29, 0xa5, 0xc4, 0x42, 0x6a, 0xa9, 0x9d, 0x7b,
	0xa8, 0xa5, 0x1a, 0xfb, 0x7a, 0x0e, 0x07, 0xf5, 0x6b, 0xc9, 0xa1, 0xea, 0x37, 0x96, 0x64, 0x1d,
	0x35, 0x8b, 0x8a, 0x76, 0xfa, 0xee, 0xfd, 0xdb, 0x75, 0xcc, 0x37, 0xe5, 0xca, 0xa3, 0x2c, 0xf5,
	0x57, 0x65, 0xb6, 0xbe, 0x28, 0x36, 0x88, 0xb9, 0xaf, 0xa3, 0x7d, 0x9a, 0x86, 0x59, 0xb8, 0xc6,
	0x14, 0x33, 0xee, 0xe7, 0x9f, 0xd6, 0x7e, 0x98, 0xc7, 0x7e, 0x35, 0xf1, 0xdb, 0xbf, 0x11, 0xab,
	0x9e, 0xfc, 0x3e, 0x3c, 0xfb, 0x1e, 0x00, 0x00, 0xff, 0xff, 0x80, 0xbe, 0x21, 0x2f, 0x7b, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactCommunicationMethodServiceClient is the client API for ContactCommunicationMethodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactCommunicationMethodServiceClient interface {
	DoRead(ctx context.Context, in *DoReadRequest, opts ...grpc.CallOption) (*DoReadResponse, error)
	DoReadAll(ctx context.Context, in *DoReadAllRequest, opts ...grpc.CallOption) (*DoReadAllResponse, error)
	DoSave(ctx context.Context, in *DoSaveRequest, opts ...grpc.CallOption) (*DoSaveResponse, error)
	DoDelete(ctx context.Context, in *DoDeleteRequest, opts ...grpc.CallOption) (*DoDeleteResponse, error)
}

type contactCommunicationMethodServiceClient struct {
	cc *grpc.ClientConn
}

func NewContactCommunicationMethodServiceClient(cc *grpc.ClientConn) ContactCommunicationMethodServiceClient {
	return &contactCommunicationMethodServiceClient{cc}
}

func (c *contactCommunicationMethodServiceClient) DoRead(ctx context.Context, in *DoReadRequest, opts ...grpc.CallOption) (*DoReadResponse, error) {
	out := new(DoReadResponse)
	err := c.cc.Invoke(ctx, "/v1.ContactCommunicationMethodService/DoRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactCommunicationMethodServiceClient) DoReadAll(ctx context.Context, in *DoReadAllRequest, opts ...grpc.CallOption) (*DoReadAllResponse, error) {
	out := new(DoReadAllResponse)
	err := c.cc.Invoke(ctx, "/v1.ContactCommunicationMethodService/DoReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactCommunicationMethodServiceClient) DoSave(ctx context.Context, in *DoSaveRequest, opts ...grpc.CallOption) (*DoSaveResponse, error) {
	out := new(DoSaveResponse)
	err := c.cc.Invoke(ctx, "/v1.ContactCommunicationMethodService/DoSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactCommunicationMethodServiceClient) DoDelete(ctx context.Context, in *DoDeleteRequest, opts ...grpc.CallOption) (*DoDeleteResponse, error) {
	out := new(DoDeleteResponse)
	err := c.cc.Invoke(ctx, "/v1.ContactCommunicationMethodService/DoDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactCommunicationMethodServiceServer is the server API for ContactCommunicationMethodService service.
type ContactCommunicationMethodServiceServer interface {
	DoRead(context.Context, *DoReadRequest) (*DoReadResponse, error)
	DoReadAll(context.Context, *DoReadAllRequest) (*DoReadAllResponse, error)
	DoSave(context.Context, *DoSaveRequest) (*DoSaveResponse, error)
	DoDelete(context.Context, *DoDeleteRequest) (*DoDeleteResponse, error)
}

// UnimplementedContactCommunicationMethodServiceServer can be embedded to have forward compatible implementations.
type UnimplementedContactCommunicationMethodServiceServer struct {
}

func (*UnimplementedContactCommunicationMethodServiceServer) DoRead(ctx context.Context, req *DoReadRequest) (*DoReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoRead not implemented")
}
func (*UnimplementedContactCommunicationMethodServiceServer) DoReadAll(ctx context.Context, req *DoReadAllRequest) (*DoReadAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoReadAll not implemented")
}
func (*UnimplementedContactCommunicationMethodServiceServer) DoSave(ctx context.Context, req *DoSaveRequest) (*DoSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSave not implemented")
}
func (*UnimplementedContactCommunicationMethodServiceServer) DoDelete(ctx context.Context, req *DoDeleteRequest) (*DoDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoDelete not implemented")
}

func RegisterContactCommunicationMethodServiceServer(s *grpc.Server, srv ContactCommunicationMethodServiceServer) {
	s.RegisterService(&_ContactCommunicationMethodService_serviceDesc, srv)
}

func _ContactCommunicationMethodService_DoRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactCommunicationMethodServiceServer).DoRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ContactCommunicationMethodService/DoRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactCommunicationMethodServiceServer).DoRead(ctx, req.(*DoReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactCommunicationMethodService_DoReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactCommunicationMethodServiceServer).DoReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ContactCommunicationMethodService/DoReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactCommunicationMethodServiceServer).DoReadAll(ctx, req.(*DoReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactCommunicationMethodService_DoSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactCommunicationMethodServiceServer).DoSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ContactCommunicationMethodService/DoSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactCommunicationMethodServiceServer).DoSave(ctx, req.(*DoSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactCommunicationMethodService_DoDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactCommunicationMethodServiceServer).DoDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ContactCommunicationMethodService/DoDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactCommunicationMethodServiceServer).DoDelete(ctx, req.(*DoDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactCommunicationMethodService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ContactCommunicationMethodService",
	HandlerType: (*ContactCommunicationMethodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoRead",
			Handler:    _ContactCommunicationMethodService_DoRead_Handler,
		},
		{
			MethodName: "DoReadAll",
			Handler:    _ContactCommunicationMethodService_DoReadAll_Handler,
		},
		{
			MethodName: "DoSave",
			Handler:    _ContactCommunicationMethodService_DoSave_Handler,
		},
		{
			MethodName: "DoDelete",
			Handler:    _ContactCommunicationMethodService_DoDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contactcommunicationmethod.proto",
}
