// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/service/v1/contactcommunicationmethod/contactcommunicationmethod.go

// Package mock_contactcommunicationmethod is a generated GoMock package.
package mock_contactcommunicationmethod

import (
	context "context"
	contactcommunicationmethod "github.com/bungysheep/contact-management/pkg/models/v1/contactcommunicationmethod"
	message "github.com/bungysheep/contact-management/pkg/models/v1/message"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIContactCommunicationMethodService is a mock of IContactCommunicationMethodService interface
type MockIContactCommunicationMethodService struct {
	ctrl     *gomock.Controller
	recorder *MockIContactCommunicationMethodServiceMockRecorder
}

// MockIContactCommunicationMethodServiceMockRecorder is the mock recorder for MockIContactCommunicationMethodService
type MockIContactCommunicationMethodServiceMockRecorder struct {
	mock *MockIContactCommunicationMethodService
}

// NewMockIContactCommunicationMethodService creates a new mock instance
func NewMockIContactCommunicationMethodService(ctrl *gomock.Controller) *MockIContactCommunicationMethodService {
	mock := &MockIContactCommunicationMethodService{ctrl: ctrl}
	mock.recorder = &MockIContactCommunicationMethodServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIContactCommunicationMethodService) EXPECT() *MockIContactCommunicationMethodServiceMockRecorder {
	return m.recorder
}

// DoRead mocks base method
func (m *MockIContactCommunicationMethodService) DoRead(arg0 context.Context, arg1 string, arg2, arg3 int64) (*contactcommunicationmethod.ContactCommunicationMethod, message.IMessage) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoRead", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*contactcommunicationmethod.ContactCommunicationMethod)
	ret1, _ := ret[1].(message.IMessage)
	return ret0, ret1
}

// DoRead indicates an expected call of DoRead
func (mr *MockIContactCommunicationMethodServiceMockRecorder) DoRead(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoRead", reflect.TypeOf((*MockIContactCommunicationMethodService)(nil).DoRead), arg0, arg1, arg2, arg3)
}

// DoReadAll mocks base method
func (m *MockIContactCommunicationMethodService) DoReadAll(arg0 context.Context, arg1 string, arg2 int64) ([]*contactcommunicationmethod.ContactCommunicationMethod, message.IMessage) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoReadAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*contactcommunicationmethod.ContactCommunicationMethod)
	ret1, _ := ret[1].(message.IMessage)
	return ret0, ret1
}

// DoReadAll indicates an expected call of DoReadAll
func (mr *MockIContactCommunicationMethodServiceMockRecorder) DoReadAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoReadAll", reflect.TypeOf((*MockIContactCommunicationMethodService)(nil).DoReadAll), arg0, arg1, arg2)
}

// DoSave mocks base method
func (m *MockIContactCommunicationMethodService) DoSave(arg0 context.Context, arg1 *contactcommunicationmethod.ContactCommunicationMethod) message.IMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoSave", arg0, arg1)
	ret0, _ := ret[0].(message.IMessage)
	return ret0
}

// DoSave indicates an expected call of DoSave
func (mr *MockIContactCommunicationMethodServiceMockRecorder) DoSave(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoSave", reflect.TypeOf((*MockIContactCommunicationMethodService)(nil).DoSave), arg0, arg1)
}

// DoDelete mocks base method
func (m *MockIContactCommunicationMethodService) DoDelete(arg0 context.Context, arg1 string, arg2, arg3 int64) message.IMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoDelete", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(message.IMessage)
	return ret0
}

// DoDelete indicates an expected call of DoDelete
func (mr *MockIContactCommunicationMethodServiceMockRecorder) DoDelete(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoDelete", reflect.TypeOf((*MockIContactCommunicationMethodService)(nil).DoDelete), arg0, arg1, arg2, arg3)
}
