// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contactsystem.proto

package contactsystem

import (
	context "context"
	fmt "fmt"
	audit "github.com/bungysheep/contact-management/pkg/api/v1/audit"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContactSystem struct {
	ContactSystemCode    string       `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Details              string       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Status               string       `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Audit                *audit.Audit `protobuf:"bytes,5,opt,name=audit,proto3" json:"audit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ContactSystem) Reset()         { *m = ContactSystem{} }
func (m *ContactSystem) String() string { return proto.CompactTextString(m) }
func (*ContactSystem) ProtoMessage()    {}
func (*ContactSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc89358642882005, []int{0}
}

func (m *ContactSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactSystem.Unmarshal(m, b)
}
func (m *ContactSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactSystem.Marshal(b, m, deterministic)
}
func (m *ContactSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactSystem.Merge(m, src)
}
func (m *ContactSystem) XXX_Size() int {
	return xxx_messageInfo_ContactSystem.Size(m)
}
func (m *ContactSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactSystem.DiscardUnknown(m)
}

var xxx_messageInfo_ContactSystem proto.InternalMessageInfo

func (m *ContactSystem) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *ContactSystem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ContactSystem) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *ContactSystem) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ContactSystem) GetAudit() *audit.Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

func init() {
	proto.RegisterType((*ContactSystem)(nil), "v1.ContactSystem")
}

func init() { proto.RegisterFile("contactsystem.proto", fileDescriptor_dc89358642882005) }

var fileDescriptor_dc89358642882005 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x14, 0x45, 0x99, 0x6a, 0x2b, 0xcd, 0xe0, 0xc2, 0x28, 0x25, 0xb8, 0x71, 0x70, 0xd5, 0x8d, 0x09,
	0x53, 0xbf, 0xa0, 0xce, 0x1f, 0xb4, 0x3b, 0x37, 0x25, 0x93, 0x3c, 0xa6, 0x41, 0x27, 0x09, 0x93,
	0x37, 0x81, 0xfe, 0x97, 0x1f, 0x28, 0x26, 0xb5, 0x74, 0x96, 0xef, 0xbc, 0x73, 0xe1, 0x72, 0xc9,
	0xa3, 0x72, 0x16, 0xa5, 0xc2, 0x70, 0x0a, 0x08, 0x3d, 0xf7, 0x83, 0x43, 0x47, 0x67, 0xb1, 0x7e,
	0x2e, 0xe5, 0xa8, 0x0d, 0x66, 0xf0, 0xfa, 0x53, 0x90, 0xfb, 0x26, 0x8b, 0xfb, 0x24, 0x52, 0x7e,
	0x49, 0x1e, 0x72, 0xf4, 0xa0, 0x9c, 0x06, 0x56, 0x54, 0xc5, 0x7a, 0xb9, 0x7b, 0x50, 0xd7, 0x6e,
	0xe3, 0x34, 0xd0, 0x8a, 0x94, 0x1a, 0x82, 0x1a, 0x8c, 0x47, 0xe3, 0x2c, 0x9b, 0x25, 0xef, 0x1a,
	0x51, 0x46, 0xee, 0x34, 0xa0, 0x34, 0xdf, 0x81, 0xdd, 0xa4, 0xef, 0xff, 0x49, 0x57, 0x64, 0x11,
	0x50, 0xe2, 0x18, 0xd8, 0x6d, 0x7a, 0x9c, 0x2f, 0xfa, 0x42, 0xe6, 0xa9, 0x24, 0x9b, 0x57, 0xc5,
	0xba, 0xdc, 0x2c, 0x79, 0xac, 0xf9, 0xf6, 0x0f, 0xec, 0x32, 0xdf, 0xac, 0xc8, 0xd3, 0xa4, 0xf5,
	0x1e, 0x86, 0x68, 0x14, 0x7c, 0x34, 0x9f, 0xdb, 0xce, 0xe0, 0x71, 0x6c, 0xb9, 0x72, 0xbd, 0x68,
	0x47, 0xdb, 0x9d, 0xc2, 0x11, 0xc0, 0x8b, 0x73, 0xef, 0xb7, 0x5e, 0x5a, 0xd9, 0x41, 0x0f, 0x16,
	0x85, 0xff, 0xea, 0x84, 0xf4, 0x46, 0xc4, 0x5a, 0x4c, 0xa6, 0x6a, 0x17, 0x69, 0x9a, 0xf7, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0xfe, 0xb8, 0x86, 0x42, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactSystemServiceClient is the client API for ContactSystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactSystemServiceClient interface {
}

type contactSystemServiceClient struct {
	cc *grpc.ClientConn
}

func NewContactSystemServiceClient(cc *grpc.ClientConn) ContactSystemServiceClient {
	return &contactSystemServiceClient{cc}
}

// ContactSystemServiceServer is the server API for ContactSystemService service.
type ContactSystemServiceServer interface {
}

// UnimplementedContactSystemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedContactSystemServiceServer struct {
}

func RegisterContactSystemServiceServer(s *grpc.Server, srv ContactSystemServiceServer) {
	s.RegisterService(&_ContactSystemService_serviceDesc, srv)
}

var _ContactSystemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ContactSystemService",
	HandlerType: (*ContactSystemServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "contactsystem.proto",
}
