// Code generated by protoc-gen-go. DO NOT EDIT.
// source: communicationmethodlabel.proto

package communicationmethodlabel

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommunicationMethodLabel struct {
	ContactSystemCode            string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode      string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	CommunicationMethodLabelCode string   `protobuf:"bytes,3,opt,name=communication_method_label_code,json=communicationMethodLabelCode,proto3" json:"communication_method_label_code,omitempty"`
	Caption                      string   `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *CommunicationMethodLabel) Reset()         { *m = CommunicationMethodLabel{} }
func (m *CommunicationMethodLabel) String() string { return proto.CompactTextString(m) }
func (*CommunicationMethodLabel) ProtoMessage()    {}
func (*CommunicationMethodLabel) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102a5fd7ad80fc5, []int{0}
}

func (m *CommunicationMethodLabel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunicationMethodLabel.Unmarshal(m, b)
}
func (m *CommunicationMethodLabel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunicationMethodLabel.Marshal(b, m, deterministic)
}
func (m *CommunicationMethodLabel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunicationMethodLabel.Merge(m, src)
}
func (m *CommunicationMethodLabel) XXX_Size() int {
	return xxx_messageInfo_CommunicationMethodLabel.Size(m)
}
func (m *CommunicationMethodLabel) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunicationMethodLabel.DiscardUnknown(m)
}

var xxx_messageInfo_CommunicationMethodLabel proto.InternalMessageInfo

func (m *CommunicationMethodLabel) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *CommunicationMethodLabel) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

func (m *CommunicationMethodLabel) GetCommunicationMethodLabelCode() string {
	if m != nil {
		return m.CommunicationMethodLabelCode
	}
	return ""
}

func (m *CommunicationMethodLabel) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

type DoReadCommunicationMethodLabelRequest struct {
	ContactSystemCode            string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode      string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	CommunicationMethodLabelCode string   `protobuf:"bytes,3,opt,name=communication_method_label_code,json=communicationMethodLabelCode,proto3" json:"communication_method_label_code,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *DoReadCommunicationMethodLabelRequest) Reset()         { *m = DoReadCommunicationMethodLabelRequest{} }
func (m *DoReadCommunicationMethodLabelRequest) String() string { return proto.CompactTextString(m) }
func (*DoReadCommunicationMethodLabelRequest) ProtoMessage()    {}
func (*DoReadCommunicationMethodLabelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102a5fd7ad80fc5, []int{1}
}

func (m *DoReadCommunicationMethodLabelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadCommunicationMethodLabelRequest.Unmarshal(m, b)
}
func (m *DoReadCommunicationMethodLabelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadCommunicationMethodLabelRequest.Marshal(b, m, deterministic)
}
func (m *DoReadCommunicationMethodLabelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadCommunicationMethodLabelRequest.Merge(m, src)
}
func (m *DoReadCommunicationMethodLabelRequest) XXX_Size() int {
	return xxx_messageInfo_DoReadCommunicationMethodLabelRequest.Size(m)
}
func (m *DoReadCommunicationMethodLabelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadCommunicationMethodLabelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadCommunicationMethodLabelRequest proto.InternalMessageInfo

func (m *DoReadCommunicationMethodLabelRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoReadCommunicationMethodLabelRequest) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

func (m *DoReadCommunicationMethodLabelRequest) GetCommunicationMethodLabelCode() string {
	if m != nil {
		return m.CommunicationMethodLabelCode
	}
	return ""
}

type DoReadCommunicationMethodLabelResponse struct {
	CommunicationMethodLabel *CommunicationMethodLabel `protobuf:"bytes,1,opt,name=communication_method_label,json=communicationMethodLabel,proto3" json:"communication_method_label,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *DoReadCommunicationMethodLabelResponse) Reset() {
	*m = DoReadCommunicationMethodLabelResponse{}
}
func (m *DoReadCommunicationMethodLabelResponse) String() string { return proto.CompactTextString(m) }
func (*DoReadCommunicationMethodLabelResponse) ProtoMessage()    {}
func (*DoReadCommunicationMethodLabelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102a5fd7ad80fc5, []int{2}
}

func (m *DoReadCommunicationMethodLabelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadCommunicationMethodLabelResponse.Unmarshal(m, b)
}
func (m *DoReadCommunicationMethodLabelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadCommunicationMethodLabelResponse.Marshal(b, m, deterministic)
}
func (m *DoReadCommunicationMethodLabelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadCommunicationMethodLabelResponse.Merge(m, src)
}
func (m *DoReadCommunicationMethodLabelResponse) XXX_Size() int {
	return xxx_messageInfo_DoReadCommunicationMethodLabelResponse.Size(m)
}
func (m *DoReadCommunicationMethodLabelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadCommunicationMethodLabelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadCommunicationMethodLabelResponse proto.InternalMessageInfo

func (m *DoReadCommunicationMethodLabelResponse) GetCommunicationMethodLabel() *CommunicationMethodLabel {
	if m != nil {
		return m.CommunicationMethodLabel
	}
	return nil
}

type DoReadAllCommunicationMethodLabelRequest struct {
	ContactSystemCode       string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DoReadAllCommunicationMethodLabelRequest) Reset() {
	*m = DoReadAllCommunicationMethodLabelRequest{}
}
func (m *DoReadAllCommunicationMethodLabelRequest) String() string { return proto.CompactTextString(m) }
func (*DoReadAllCommunicationMethodLabelRequest) ProtoMessage()    {}
func (*DoReadAllCommunicationMethodLabelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102a5fd7ad80fc5, []int{3}
}

func (m *DoReadAllCommunicationMethodLabelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadAllCommunicationMethodLabelRequest.Unmarshal(m, b)
}
func (m *DoReadAllCommunicationMethodLabelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadAllCommunicationMethodLabelRequest.Marshal(b, m, deterministic)
}
func (m *DoReadAllCommunicationMethodLabelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadAllCommunicationMethodLabelRequest.Merge(m, src)
}
func (m *DoReadAllCommunicationMethodLabelRequest) XXX_Size() int {
	return xxx_messageInfo_DoReadAllCommunicationMethodLabelRequest.Size(m)
}
func (m *DoReadAllCommunicationMethodLabelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadAllCommunicationMethodLabelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadAllCommunicationMethodLabelRequest proto.InternalMessageInfo

func (m *DoReadAllCommunicationMethodLabelRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoReadAllCommunicationMethodLabelRequest) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

type DoReadAllCommunicationMethodLabelResponse struct {
	CommunicationMethodLabel []*CommunicationMethodLabel `protobuf:"bytes,1,rep,name=communication_method_label,json=communicationMethodLabel,proto3" json:"communication_method_label,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                    `json:"-"`
	XXX_unrecognized         []byte                      `json:"-"`
	XXX_sizecache            int32                       `json:"-"`
}

func (m *DoReadAllCommunicationMethodLabelResponse) Reset() {
	*m = DoReadAllCommunicationMethodLabelResponse{}
}
func (m *DoReadAllCommunicationMethodLabelResponse) String() string { return proto.CompactTextString(m) }
func (*DoReadAllCommunicationMethodLabelResponse) ProtoMessage()    {}
func (*DoReadAllCommunicationMethodLabelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102a5fd7ad80fc5, []int{4}
}

func (m *DoReadAllCommunicationMethodLabelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoReadAllCommunicationMethodLabelResponse.Unmarshal(m, b)
}
func (m *DoReadAllCommunicationMethodLabelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoReadAllCommunicationMethodLabelResponse.Marshal(b, m, deterministic)
}
func (m *DoReadAllCommunicationMethodLabelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoReadAllCommunicationMethodLabelResponse.Merge(m, src)
}
func (m *DoReadAllCommunicationMethodLabelResponse) XXX_Size() int {
	return xxx_messageInfo_DoReadAllCommunicationMethodLabelResponse.Size(m)
}
func (m *DoReadAllCommunicationMethodLabelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoReadAllCommunicationMethodLabelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoReadAllCommunicationMethodLabelResponse proto.InternalMessageInfo

func (m *DoReadAllCommunicationMethodLabelResponse) GetCommunicationMethodLabel() []*CommunicationMethodLabel {
	if m != nil {
		return m.CommunicationMethodLabel
	}
	return nil
}

type DoSaveCommunicationMethodLabelRequest struct {
	CommunicationMethodLabel *CommunicationMethodLabel `protobuf:"bytes,1,opt,name=communication_method_label,json=communicationMethodLabel,proto3" json:"communication_method_label,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *DoSaveCommunicationMethodLabelRequest) Reset()         { *m = DoSaveCommunicationMethodLabelRequest{} }
func (m *DoSaveCommunicationMethodLabelRequest) String() string { return proto.CompactTextString(m) }
func (*DoSaveCommunicationMethodLabelRequest) ProtoMessage()    {}
func (*DoSaveCommunicationMethodLabelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102a5fd7ad80fc5, []int{5}
}

func (m *DoSaveCommunicationMethodLabelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSaveCommunicationMethodLabelRequest.Unmarshal(m, b)
}
func (m *DoSaveCommunicationMethodLabelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSaveCommunicationMethodLabelRequest.Marshal(b, m, deterministic)
}
func (m *DoSaveCommunicationMethodLabelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSaveCommunicationMethodLabelRequest.Merge(m, src)
}
func (m *DoSaveCommunicationMethodLabelRequest) XXX_Size() int {
	return xxx_messageInfo_DoSaveCommunicationMethodLabelRequest.Size(m)
}
func (m *DoSaveCommunicationMethodLabelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSaveCommunicationMethodLabelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoSaveCommunicationMethodLabelRequest proto.InternalMessageInfo

func (m *DoSaveCommunicationMethodLabelRequest) GetCommunicationMethodLabel() *CommunicationMethodLabel {
	if m != nil {
		return m.CommunicationMethodLabel
	}
	return nil
}

type DoSaveCommunicationMethodLabelResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoSaveCommunicationMethodLabelResponse) Reset() {
	*m = DoSaveCommunicationMethodLabelResponse{}
}
func (m *DoSaveCommunicationMethodLabelResponse) String() string { return proto.CompactTextString(m) }
func (*DoSaveCommunicationMethodLabelResponse) ProtoMessage()    {}
func (*DoSaveCommunicationMethodLabelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102a5fd7ad80fc5, []int{6}
}

func (m *DoSaveCommunicationMethodLabelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSaveCommunicationMethodLabelResponse.Unmarshal(m, b)
}
func (m *DoSaveCommunicationMethodLabelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSaveCommunicationMethodLabelResponse.Marshal(b, m, deterministic)
}
func (m *DoSaveCommunicationMethodLabelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSaveCommunicationMethodLabelResponse.Merge(m, src)
}
func (m *DoSaveCommunicationMethodLabelResponse) XXX_Size() int {
	return xxx_messageInfo_DoSaveCommunicationMethodLabelResponse.Size(m)
}
func (m *DoSaveCommunicationMethodLabelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSaveCommunicationMethodLabelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoSaveCommunicationMethodLabelResponse proto.InternalMessageInfo

func (m *DoSaveCommunicationMethodLabelResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type DoDeleteCommunicationMethodLabelRequest struct {
	ContactSystemCode            string   `protobuf:"bytes,1,opt,name=contact_system_code,json=contactSystemCode,proto3" json:"contact_system_code,omitempty"`
	CommunicationMethodCode      string   `protobuf:"bytes,2,opt,name=communication_method_code,json=communicationMethodCode,proto3" json:"communication_method_code,omitempty"`
	CommunicationMethodLabelCode string   `protobuf:"bytes,3,opt,name=communication_method_label_code,json=communicationMethodLabelCode,proto3" json:"communication_method_label_code,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *DoDeleteCommunicationMethodLabelRequest) Reset() {
	*m = DoDeleteCommunicationMethodLabelRequest{}
}
func (m *DoDeleteCommunicationMethodLabelRequest) String() string { return proto.CompactTextString(m) }
func (*DoDeleteCommunicationMethodLabelRequest) ProtoMessage()    {}
func (*DoDeleteCommunicationMethodLabelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102a5fd7ad80fc5, []int{7}
}

func (m *DoDeleteCommunicationMethodLabelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoDeleteCommunicationMethodLabelRequest.Unmarshal(m, b)
}
func (m *DoDeleteCommunicationMethodLabelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoDeleteCommunicationMethodLabelRequest.Marshal(b, m, deterministic)
}
func (m *DoDeleteCommunicationMethodLabelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoDeleteCommunicationMethodLabelRequest.Merge(m, src)
}
func (m *DoDeleteCommunicationMethodLabelRequest) XXX_Size() int {
	return xxx_messageInfo_DoDeleteCommunicationMethodLabelRequest.Size(m)
}
func (m *DoDeleteCommunicationMethodLabelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoDeleteCommunicationMethodLabelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoDeleteCommunicationMethodLabelRequest proto.InternalMessageInfo

func (m *DoDeleteCommunicationMethodLabelRequest) GetContactSystemCode() string {
	if m != nil {
		return m.ContactSystemCode
	}
	return ""
}

func (m *DoDeleteCommunicationMethodLabelRequest) GetCommunicationMethodCode() string {
	if m != nil {
		return m.CommunicationMethodCode
	}
	return ""
}

func (m *DoDeleteCommunicationMethodLabelRequest) GetCommunicationMethodLabelCode() string {
	if m != nil {
		return m.CommunicationMethodLabelCode
	}
	return ""
}

type DoDeleteCommunicationMethodLabelResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoDeleteCommunicationMethodLabelResponse) Reset() {
	*m = DoDeleteCommunicationMethodLabelResponse{}
}
func (m *DoDeleteCommunicationMethodLabelResponse) String() string { return proto.CompactTextString(m) }
func (*DoDeleteCommunicationMethodLabelResponse) ProtoMessage()    {}
func (*DoDeleteCommunicationMethodLabelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102a5fd7ad80fc5, []int{8}
}

func (m *DoDeleteCommunicationMethodLabelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoDeleteCommunicationMethodLabelResponse.Unmarshal(m, b)
}
func (m *DoDeleteCommunicationMethodLabelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoDeleteCommunicationMethodLabelResponse.Marshal(b, m, deterministic)
}
func (m *DoDeleteCommunicationMethodLabelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoDeleteCommunicationMethodLabelResponse.Merge(m, src)
}
func (m *DoDeleteCommunicationMethodLabelResponse) XXX_Size() int {
	return xxx_messageInfo_DoDeleteCommunicationMethodLabelResponse.Size(m)
}
func (m *DoDeleteCommunicationMethodLabelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoDeleteCommunicationMethodLabelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoDeleteCommunicationMethodLabelResponse proto.InternalMessageInfo

func (m *DoDeleteCommunicationMethodLabelResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*CommunicationMethodLabel)(nil), "v1.CommunicationMethodLabel")
	proto.RegisterType((*DoReadCommunicationMethodLabelRequest)(nil), "v1.DoReadCommunicationMethodLabelRequest")
	proto.RegisterType((*DoReadCommunicationMethodLabelResponse)(nil), "v1.DoReadCommunicationMethodLabelResponse")
	proto.RegisterType((*DoReadAllCommunicationMethodLabelRequest)(nil), "v1.DoReadAllCommunicationMethodLabelRequest")
	proto.RegisterType((*DoReadAllCommunicationMethodLabelResponse)(nil), "v1.DoReadAllCommunicationMethodLabelResponse")
	proto.RegisterType((*DoSaveCommunicationMethodLabelRequest)(nil), "v1.DoSaveCommunicationMethodLabelRequest")
	proto.RegisterType((*DoSaveCommunicationMethodLabelResponse)(nil), "v1.DoSaveCommunicationMethodLabelResponse")
	proto.RegisterType((*DoDeleteCommunicationMethodLabelRequest)(nil), "v1.DoDeleteCommunicationMethodLabelRequest")
	proto.RegisterType((*DoDeleteCommunicationMethodLabelResponse)(nil), "v1.DoDeleteCommunicationMethodLabelResponse")
}

func init() { proto.RegisterFile("communicationmethodlabel.proto", fileDescriptor_4102a5fd7ad80fc5) }

var fileDescriptor_4102a5fd7ad80fc5 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0xcd, 0xae, 0x93, 0x40,
	0x18, 0xcd, 0xdc, 0x9a, 0x7a, 0xef, 0xe7, 0xca, 0x31, 0x51, 0x24, 0x37, 0x5e, 0x43, 0xa2, 0xde,
	0x6a, 0x0b, 0x69, 0xdd, 0xb9, 0xd2, 0xb6, 0xee, 0xaa, 0x0b, 0xba, 0xeb, 0x86, 0x0c, 0xc3, 0x17,
	0x20, 0x02, 0x83, 0x65, 0x20, 0xe9, 0x5a, 0x13, 0xdf, 0xc0, 0x27, 0xf1, 0x69, 0x8c, 0x7b, 0x5f,
	0xc3, 0x30, 0x80, 0x3f, 0x51, 0xca, 0x24, 0xc6, 0x44, 0x5d, 0x92, 0x39, 0xe7, 0x3b, 0xe7, 0x7c,
	0x73, 0x00, 0xb8, 0xc3, 0x45, 0x9a, 0x96, 0x59, 0xcc, 0x99, 0x8c, 0x45, 0x96, 0xa2, 0x8c, 0x44,
	0x90, 0x30, 0x1f, 0x13, 0x3b, 0xdf, 0x0b, 0x29, 0xe8, 0x49, 0x35, 0xb7, 0x3e, 0x13, 0x30, 0x56,
	0xdf, 0xc3, 0x5e, 0x28, 0xd8, 0xa6, 0x86, 0x51, 0x1b, 0x6e, 0x70, 0x91, 0x49, 0xc6, 0xa5, 0x57,
	0x1c, 0x0a, 0x89, 0xa9, 0xc7, 0x45, 0x80, 0x06, 0xb9, 0x4b, 0x2e, 0xcf, 0xdc, 0xeb, 0xed, 0xd1,
	0x56, 0x9d, 0xac, 0x44, 0x80, 0xf4, 0x09, 0xdc, 0xfe, 0x41, 0xd2, 0x6b, 0x34, 0x1b, 0xd6, 0x89,
	0x62, 0xdd, 0xe2, 0x3f, 0x8b, 0x29, 0xee, 0x73, 0xb8, 0xf8, 0x25, 0x57, 0x19, 0x6e, 0x26, 0x8c,
	0xd4, 0x84, 0x73, 0xde, 0x63, 0x57, 0x8d, 0x31, 0xe0, 0x2a, 0x67, 0x79, 0x7d, 0x62, 0x5c, 0x51,
	0xf0, 0xee, 0xd1, 0xfa, 0x48, 0xe0, 0xde, 0x5a, 0xb8, 0xc8, 0x82, 0xbe, 0xbc, 0x2e, 0xbe, 0x2e,
	0xb1, 0x90, 0xff, 0x60, 0x6c, 0xeb, 0x2d, 0x81, 0xfb, 0x43, 0xe1, 0x8a, 0x5c, 0x64, 0x05, 0xd2,
	0x1d, 0x98, 0xfd, 0x8a, 0x2a, 0xe4, 0xb5, 0xc5, 0xb9, 0x5d, 0xcd, 0xed, 0xde, 0x49, 0x46, 0x9f,
	0x15, 0xeb, 0x3d, 0x81, 0xcb, 0xc6, 0xc6, 0xb3, 0x24, 0xf9, 0x8b, 0xd6, 0x6c, 0xbd, 0x23, 0x30,
	0xd1, 0x30, 0xa6, 0xb9, 0xa2, 0xd1, 0x6f, 0xac, 0xe8, 0x8d, 0xaa, 0xe1, 0x96, 0x55, 0x38, 0xb4,
	0x9f, 0x3f, 0x79, 0x51, 0x4f, 0xeb, 0xba, 0x1c, 0x37, 0xd1, 0xee, 0xe2, 0x26, 0x8c, 0xf7, 0x58,
	0x94, 0x89, 0x54, 0x8a, 0xa7, 0x6e, 0xfb, 0x64, 0x7d, 0x22, 0xf0, 0x60, 0x2d, 0xd6, 0x98, 0xa0,
	0xc4, 0xff, 0xf0, 0x85, 0x5a, 0xd6, 0x45, 0x1e, 0x4a, 0x77, 0x7c, 0x45, 0x8b, 0x0f, 0x23, 0xb8,
	0xe8, 0x23, 0x6f, 0x71, 0x5f, 0xc5, 0x1c, 0xa9, 0x07, 0xe3, 0xa6, 0x97, 0x74, 0x52, 0x5f, 0xa5,
	0xd6, 0x07, 0xca, 0x7c, 0xa8, 0x03, 0x6d, 0xcd, 0x45, 0x70, 0xf6, 0xb5, 0xf8, 0x74, 0xfa, 0x8d,
	0x38, 0xfc, 0x82, 0x9a, 0x33, 0x4d, 0x74, 0xab, 0xa4, 0xa2, 0xd4, 0x9d, 0xea, 0xa2, 0x68, 0x94,
	0xbc, 0x8b, 0xa2, 0x55, 0x45, 0x84, 0xd3, 0xee, 0x4e, 0xe8, 0xa3, 0x86, 0xa7, 0xd5, 0x3f, 0x73,
	0xaa, 0x07, 0x6e, 0x64, 0x96, 0x2f, 0x77, 0x9b, 0x30, 0x96, 0x51, 0xe9, 0xdb, 0x5c, 0xa4, 0x8e,
	0x5f, 0x66, 0xe1, 0xa1, 0x88, 0x10, 0x73, 0xa7, 0x2d, 0xea, 0x2c, 0x65, 0x19, 0x0b, 0x31, 0xc5,
	0x4c, 0x3a, 0xf9, 0xab, 0xd0, 0x61, 0x79, 0xec, 0x54, 0x73, 0xa7, 0xef, 0x67, 0xeb, 0x8f, 0xd5,
	0xdf, 0xf6, 0xf1, 0x97, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x61, 0xea, 0x16, 0x8f, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommunicationMethodLabelServiceClient is the client API for CommunicationMethodLabelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommunicationMethodLabelServiceClient interface {
	DoRead(ctx context.Context, in *DoReadCommunicationMethodLabelRequest, opts ...grpc.CallOption) (*DoReadCommunicationMethodLabelResponse, error)
	DoReadAll(ctx context.Context, in *DoReadAllCommunicationMethodLabelRequest, opts ...grpc.CallOption) (*DoReadAllCommunicationMethodLabelResponse, error)
	DoSave(ctx context.Context, in *DoSaveCommunicationMethodLabelRequest, opts ...grpc.CallOption) (*DoSaveCommunicationMethodLabelResponse, error)
	DoDelete(ctx context.Context, in *DoDeleteCommunicationMethodLabelRequest, opts ...grpc.CallOption) (*DoDeleteCommunicationMethodLabelResponse, error)
}

type communicationMethodLabelServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommunicationMethodLabelServiceClient(cc *grpc.ClientConn) CommunicationMethodLabelServiceClient {
	return &communicationMethodLabelServiceClient{cc}
}

func (c *communicationMethodLabelServiceClient) DoRead(ctx context.Context, in *DoReadCommunicationMethodLabelRequest, opts ...grpc.CallOption) (*DoReadCommunicationMethodLabelResponse, error) {
	out := new(DoReadCommunicationMethodLabelResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodLabelService/DoRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodLabelServiceClient) DoReadAll(ctx context.Context, in *DoReadAllCommunicationMethodLabelRequest, opts ...grpc.CallOption) (*DoReadAllCommunicationMethodLabelResponse, error) {
	out := new(DoReadAllCommunicationMethodLabelResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodLabelService/DoReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodLabelServiceClient) DoSave(ctx context.Context, in *DoSaveCommunicationMethodLabelRequest, opts ...grpc.CallOption) (*DoSaveCommunicationMethodLabelResponse, error) {
	out := new(DoSaveCommunicationMethodLabelResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodLabelService/DoSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationMethodLabelServiceClient) DoDelete(ctx context.Context, in *DoDeleteCommunicationMethodLabelRequest, opts ...grpc.CallOption) (*DoDeleteCommunicationMethodLabelResponse, error) {
	out := new(DoDeleteCommunicationMethodLabelResponse)
	err := c.cc.Invoke(ctx, "/v1.CommunicationMethodLabelService/DoDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicationMethodLabelServiceServer is the server API for CommunicationMethodLabelService service.
type CommunicationMethodLabelServiceServer interface {
	DoRead(context.Context, *DoReadCommunicationMethodLabelRequest) (*DoReadCommunicationMethodLabelResponse, error)
	DoReadAll(context.Context, *DoReadAllCommunicationMethodLabelRequest) (*DoReadAllCommunicationMethodLabelResponse, error)
	DoSave(context.Context, *DoSaveCommunicationMethodLabelRequest) (*DoSaveCommunicationMethodLabelResponse, error)
	DoDelete(context.Context, *DoDeleteCommunicationMethodLabelRequest) (*DoDeleteCommunicationMethodLabelResponse, error)
}

// UnimplementedCommunicationMethodLabelServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommunicationMethodLabelServiceServer struct {
}

func (*UnimplementedCommunicationMethodLabelServiceServer) DoRead(ctx context.Context, req *DoReadCommunicationMethodLabelRequest) (*DoReadCommunicationMethodLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoRead not implemented")
}
func (*UnimplementedCommunicationMethodLabelServiceServer) DoReadAll(ctx context.Context, req *DoReadAllCommunicationMethodLabelRequest) (*DoReadAllCommunicationMethodLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoReadAll not implemented")
}
func (*UnimplementedCommunicationMethodLabelServiceServer) DoSave(ctx context.Context, req *DoSaveCommunicationMethodLabelRequest) (*DoSaveCommunicationMethodLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSave not implemented")
}
func (*UnimplementedCommunicationMethodLabelServiceServer) DoDelete(ctx context.Context, req *DoDeleteCommunicationMethodLabelRequest) (*DoDeleteCommunicationMethodLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoDelete not implemented")
}

func RegisterCommunicationMethodLabelServiceServer(s *grpc.Server, srv CommunicationMethodLabelServiceServer) {
	s.RegisterService(&_CommunicationMethodLabelService_serviceDesc, srv)
}

func _CommunicationMethodLabelService_DoRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReadCommunicationMethodLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodLabelServiceServer).DoRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodLabelService/DoRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodLabelServiceServer).DoRead(ctx, req.(*DoReadCommunicationMethodLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodLabelService_DoReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReadAllCommunicationMethodLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodLabelServiceServer).DoReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodLabelService/DoReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodLabelServiceServer).DoReadAll(ctx, req.(*DoReadAllCommunicationMethodLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodLabelService_DoSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoSaveCommunicationMethodLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodLabelServiceServer).DoSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodLabelService/DoSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodLabelServiceServer).DoSave(ctx, req.(*DoSaveCommunicationMethodLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationMethodLabelService_DoDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoDeleteCommunicationMethodLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationMethodLabelServiceServer).DoDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CommunicationMethodLabelService/DoDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationMethodLabelServiceServer).DoDelete(ctx, req.(*DoDeleteCommunicationMethodLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommunicationMethodLabelService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CommunicationMethodLabelService",
	HandlerType: (*CommunicationMethodLabelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoRead",
			Handler:    _CommunicationMethodLabelService_DoRead_Handler,
		},
		{
			MethodName: "DoReadAll",
			Handler:    _CommunicationMethodLabelService_DoReadAll_Handler,
		},
		{
			MethodName: "DoSave",
			Handler:    _CommunicationMethodLabelService_DoSave_Handler,
		},
		{
			MethodName: "DoDelete",
			Handler:    _CommunicationMethodLabelService_DoDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communicationmethodlabel.proto",
}
